//--------------------------------------------------------------------------|
// This file was initially generated by the EspritAddInProjectWizard.       |
// Portions Copyright © 2011-2020 DP Technology Corp.                       |
//                                                                          |
// You have a royalty-free right to use, modify, reproduce and distribute   |
// this file (and/or any modified or compiled version of it) in any way     |
// you see fit, provided that you agree that DP Technology has no warranty  |
// obligations or liability whatsoever for this file or for the results of  |
// your use of it or any modified or compiled version of it you may make.   |
//--------------------------------------------------------------------------'

using DPTechnology.AnnexLibraries;
using DPTechnology.AnnexLibraries.EspritAnnex;
using Microsoft.Win32;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using Esprit;
using System.IO;


namespace Acrodent.EspritAddIns.ESPRIT2025AddinProject
{

    [ClassInterface(ClassInterfaceType.None), ComVisible(true),
        Guid("1c4198bd-2143-470a-a041-93f2ebf4c904"),
        ProgId("ESPRIT2025AddinProject.Connect")]
    public class Connect : DPTechnology.AnnexLibraries.EspritAddIn
    {

        // Default Property Procedures should not need changes
        #region " Default Property Procedures "

        private DPTechnology.AnnexLibraries.IConnectionManager _ConnectionManager;
        protected override DPTechnology.AnnexLibraries.IConnectionManager ConnectionManager
        {
            get
            {
                if (_ConnectionManager == null)
                {
                    _ConnectionManager = new DPTechnology.AnnexLibraries.EspritAnnex.ConnectionManager();
                    _ConnectionManager.AddInConnect += _ConnectionManager_AddInConnect;
                    _ConnectionManager.AddInDisconnect += _ConnectionManager_AddInDisconnect;
                    _ConnectionManager.DocumentClosed += _ConnectionManager_DocumentClosed;
                    _ConnectionManager.DocumentInitialize += _ConnectionManager_DocumentInitialize;
                    _ConnectionManager.EspritApplicationShutdown += _ConnectionManager_EspritApplicationShutdown;
                }
                return _ConnectionManager;
            }
        }

        public override string Description
        {
            // To modify the AddInDescription go to the Resources tab in the project Properties.
            get { return Properties.Resources.AddInDescription; }
        }

        public override string FriendlyName
        {
            // To modify the AddInFriendlyName go to the Resources tab in the project Properties.
            get { return Properties.Resources.AddInFriendlyName; }
        }

        public override string Name
        {
            get { return System.Reflection.Assembly.GetExecutingAssembly().GetName().Name; }
        }

        public override System.Diagnostics.TraceLevel OutputWindowTraceLevel
        {
            // To modify the OutputWindowTraceLevel go to the Settings tab in the project Properties.
            get { return Properties.Settings.Default.OutputWindowTraceLevel; }
        }

        protected override Nullable<Int32> PreviousLanguage
        {
            get
            {
                Int32 returnValue;
                if (Int32.TryParse(Properties.Settings.Default.PreviousLanguage, out returnValue))
                    { return returnValue; }
                else
                    { return null; }
            }
            set
            {
                if (value.HasValue)
                {
                    Properties.Settings.Default.PreviousLanguage = value.Value.ToString();
                    Properties.Settings.Default.Save();
                }
            }
        }

        protected override System.Globalization.CultureInfo ResourcesCulture
        {
            get { return Properties.Resources.Culture; }
            set { Properties.Resources.Culture = value; }
        }

        #endregion

        private const string regSettings = "Settings:";
        private const string regPositionDock = "Dock";
        private const string regPositionTop = "Top";
        private const string regPositionLeft = "Left";
        private const string regPositionWidth = "Width";
        private const string regPositionHeight = "Height";

        public static Esprit.Application _espApp;
        public Esprit.ToolBar _newToolbar;

        public EspritMenus.Menu _tbMenu = default(EspritMenus.Menu);
        public EspritMenus.MenuItem _tbMenuItem = default(EspritMenus.MenuItem);

        public List<int> _iCNumbs = new List<int>();
        public const string _toolbarName = "Acrodent_addin";

        public static int _iCntOfCommands = 1;
        public Esprit.PMTab exTab;
        public Esprit.ProjectManager _pm;

        public static int _MyCookie;

        // New flag to ensure toolbar position is applied only once
        private bool _toolbarPositionLoaded = false;
        
        public void _ConnectionManager_AddInConnect(Esprit.Application espritApplication)
        {
            // If an Esprit.Application object property or variable is declared in your project you can assign it from here.
            //        
            // Since the EspritAddIn base class that is inherited handles the Document related Application events for you,
            // you should only need a WithEvents Esprit.Application for other non-Document related events, like AfterCommandRun.
            //        
            // This event can be removed if it does not need to be used (e.g. if you only need an Esprit.Document or Esprit.Document members).
            _espApp = espritApplication;
            _pm = _espApp.ProjectManager;

            // -------------------------
            // 1. Apply commands
            // -------------------------
            var EC = espritApplication.AddIn as EspritCommands.AddIn;
            _MyCookie = EC.GetCookie();

            _espApp.ToolBars.Remove(_toolbarName);
            _newToolbar = _espApp.ToolBars.Add(_toolbarName);
            for (int i = 0; i < _iCntOfCommands; i++)
            {
                _iCNumbs.Add(EC.AddCommand(_MyCookie, i, "Acrodent Command " + i));
            }

            for (int i = 0; i < _iCntOfCommands; i++)
            {
                Esprit.ToolBarControl tbcon = _newToolbar.Add(EspritConstants.espToolBarControl.espToolBarControlButton, "acrodent_Addin_" + i.ToString(), _iCNumbs[i]);
                tbcon.SetBitmap(Path.Combine(Directory.GetCurrentDirectory(), "tooth_16.bmp"), Path.Combine(Directory.GetCurrentDirectory(), "tooth_32.bmp"));
                tbcon.Enabled = true;
                tbcon.Name = "Acrodent command " + i.ToString();
            }

            //EC.OnCommand;
            EC.OnCommand += EC_OnCommand;

            // -------------------------
            // 2. Commands on View menu
            // -------------------------

            EspritMenus.Menus myMenu = _espApp.Menus as EspritMenus.Menus;
            _tbMenu = myMenu["&View"]["&Toolbars..."].SubMenu;
            _tbMenu.Remove(_toolbarName);
            _tbMenuItem = _tbMenu.Add(EspritConstants.espMenuItemType.espMenuItemCommand, _toolbarName, _iCNumbs[0]);

            // -------------------------
            // 3. Commands on Tool sub menu
            // -------------------------

            _tbMenu = myMenu["&Tools"];
            _tbMenu.Remove(_toolbarName);

            if (_tbMenu[_tbMenu.Count].Type == EspritConstants.espMenuItemType.espMenuItemSeparator)
                _tbMenu.Remove(_tbMenu.Count);
            _tbMenu.Add(EspritConstants.espMenuItemType.espMenuItemSeparator);
            _tbMenu.Add(EspritConstants.espMenuItemType.espMenuItemPopUp, _toolbarName);
            _tbMenu = myMenu["&Tools"][_toolbarName].SubMenu;

            _tbMenu.Add(EspritConstants.espMenuItemType.espMenuItemCommand, "Command 1", _iCNumbs[0]);

            // Ensure toolbar position is applied after toolbar/menu creation.
            // This makes sure position loading occurs after the application has initialized UI elements.
            try
            {
                if (!_toolbarPositionLoaded && _newToolbar != null)
                {
                    Toolbar_PositionLoad(_toolbarName, _newToolbar);
                    _toolbarPositionLoaded = true;
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Trace.WriteLine($"Connect: Failed to load toolbar position in AddInConnect: {ex}");
            }
        }


        private void EC_OnCommand(int Cookie, int UserId)
        {
            if (Cookie != _MyCookie)
                return;

            switch (UserId)
            {
                case 0:
                    //DentalAddin.DentalPanel da = new DentalAddin.DentalPanel();
                    //
                    //exTab = ApplicationUtilities.AddProjectManagerTab(da);
                    //ApplicationUtilities.TryActivateProjectManagerTab(exTab.HWND);
                    //
                    //da.InputFPointVal(1.23);
                    //da.InputBPointVal(4.56);

                    // TODO : put your folder path as second argument of RepeatProcess constructor
                    // e.g.: RepeatProcess rp = new RepeatProcess(_espApp, @"C:\STLFiles");
                    RepeatProcess rp = new RepeatProcess(_espApp);
                    rp.Run();

                    break;
            }
        }

        public void _ConnectionManager_AddInDisconnect()
        {
            // Triggered when the Add-In disconnects because it was Unloaded from the Add-In Manager.
            // This means ESPRIT will remain running; otherwise only EspritApplicationShutdown is triggered.
            // This event procedure can be removed if it does not need to be used.
            _pm.PMTabs.Remove(exTab.HWND);
        }

        public void _ConnectionManager_DocumentClosed(bool espritIsShuttingDown)
        {
            // Triggered after the Document has been closed.
            // The Boolean argument signals whether or not the Document was closed because ESPRIT is shutting down.
            // This event procedure can be removed if it does not need to be used.
        }

        public void _ConnectionManager_DocumentInitialize(Esprit.Document espritDocument, string fileName)
        {
            // Triggered whenever the Document object has been re-initialized.
            //
            // If an Esprit.Document object property or variable is declared in your project you can assign it from here.
            // Procedures that apply to both New and existing ESPRIT files can then be called here also.
            //
            // Note that a Null filename (Nothing) indicates a New Document (AfterNewDocumentOpen event),
            // while a non-null filename could be an existing file (AfterDocumentOpen or AfterTemplateOpen event),
            // or could indicate connection to a running Esprit.Application that had a Document already open.
            // In the latter case the filename will not be null, but could be Empty to indicate an unsaved Document.
            //
            if (fileName == null) { return; }
            // Procedures that apply only when opening existing files (and not staring New ones) can be called here.
            //
            // This event procedure can be removed if it does not need to be used (but that is rarely the case).

            // Call toolbar position load only if it has not already been applied.
            if (!_toolbarPositionLoaded && _newToolbar != null)
            {
                try
                {
                    Toolbar_PositionLoad(_toolbarName, _newToolbar);
                    _toolbarPositionLoaded = true;
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Trace.WriteLine($"Connect: Failed to load toolbar position in DocumentInitialize: {ex}");
                }
            }
        }

        public void _ConnectionManager_EspritApplicationShutdown()
        {
            // Triggered when the Add-In disconnects explicitly because ESPRIT is shutting down.
            // This event can be removed if it does not need to be used.
            Toolbar_PositionSave(_toolbarName, _newToolbar);
        }

        #region TOOLBAR_POSITION
        private void Toolbar_PositionSave(string aToolbarName, Esprit.ToolBar aToolbarObject)
        {
            if (aToolbarObject == null) return;
            WriteReg(regPositionDock, aToolbarObject.Position.ToString());
            WriteReg(regPositionTop, aToolbarObject.Top.ToString());
            WriteReg(regPositionLeft, aToolbarObject.Left.ToString());
            WriteReg(regPositionWidth, aToolbarObject.Width.ToString());
            WriteReg(regPositionHeight, aToolbarObject.Height.ToString());
        }

        private void Toolbar_PositionLoad(string aToolbarName, Esprit.ToolBar aToolbarObject)
        {

            string pos = ReadReg(regPositionDock);
            switch (pos)
            {
                case "espToolBarPositionFloating":
                    {
                        //aToolbarObject.Dock(EspritConstants.espToolBarPosition.espToolBarPositionFloating);
                        break;
                    }
                case "espToolBarPositionTop":
                    {
                        aToolbarObject.Dock(EspritConstants.espToolBarPosition.espToolBarPositionTop);
                        break;
                    }
                case "espToolBarPositionLeft":
                    {
                        aToolbarObject.Dock(EspritConstants.espToolBarPosition.espToolBarPositionLeft);
                        break;
                    }
                case "espToolBarPositionBottom":
                    {
                        aToolbarObject.Dock(EspritConstants.espToolBarPosition.espToolBarPositionBottom);
                        break;
                    }
                case "espToolBarPositionRight":
                    {
                        aToolbarObject.Dock(EspritConstants.espToolBarPosition.espToolBarPositionRight);
                        break;
                    }
            }
            //aToolbarObject.Dock(EspritConstants.espToolBarPosition.espToolBarPositionFloating);
            switch (aToolbarObject.Position)
            {
                case EspritConstants.espToolBarPosition.espToolBarPositionBottom:
                    {
                        aToolbarObject.Top = Convert.ToInt32(ReadReg(regPositionTop)) + aToolbarObject.Height;
                        aToolbarObject.Left = Convert.ToInt32(ReadReg(regPositionLeft));
                        break;
                    }
                case EspritConstants.espToolBarPosition.espToolBarPositionLeft:
                    {
                        aToolbarObject.Top = Convert.ToInt32(ReadReg(regPositionTop));
                        aToolbarObject.Left = Convert.ToInt32(ReadReg(regPositionLeft)) + aToolbarObject.Width;
                        break;
                    }
                case EspritConstants.espToolBarPosition.espToolBarPositionRight:
                    {
                        aToolbarObject.Top = Convert.ToInt32(ReadReg(regPositionTop));
                        aToolbarObject.Left = Convert.ToInt32(ReadReg(regPositionLeft));
                        break;
                    }
                case EspritConstants.espToolBarPosition.espToolBarPositionTop:
                    {
                        aToolbarObject.Top = Convert.ToInt32(ReadReg(regPositionTop));
                        aToolbarObject.Left = Convert.ToInt32(ReadReg(regPositionLeft));
                        break;
                    }
            }
        }
        #endregion TOOLBAR_POSITION

        #region Registry_Read_Write
        private string ReadReg(string valueName)
        {
            const string userRoot = "HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\D.P.Technology\\ESPRIT\\AddIns";
            const string subkey = "ESPRIT2025AddinProject.Connect\\" + regSettings + _toolbarName + ".ToolBar";
            const string keyName = userRoot + "\\" + subkey;
            var val = Registry.GetValue(keyName, valueName, "");
            if(val == null)
                return "";
            string tStr = Registry.GetValue(keyName, valueName, "").ToString();
            return tStr;
        }

        void WriteReg(string valueName, string POSvalue)
        {
            const string userRoot = "HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\D.P.Technology\\ESPRIT\\AddIns";
            const string subkey = "ESPRIT2025AddinProject.Connect\\" + regSettings + _toolbarName + ".ToolBar";
            const string keyName = userRoot + "\\" + subkey;
            Registry.SetValue(keyName, valueName, POSvalue, RegistryValueKind.String);
        }
        #endregion Registry_Read_Write
    }

}
