//--------------------------------------------------------------------------|
// This file was initially generated by the EspritAddInProjectWizard.       |
// Portions Copyright © 2011-2020 DP Technology Corp.                       |
//                                                                          |
// You have a royalty-free right to use, modify, reproduce and distribute   |
// this file (and/or any modified or compiled version of it) in any way     |
// you see fit, provided that you agree that DP Technology has no warranty  |
// obligations or liability whatsoever for this file or for the results of  |
// your use of it or any modified or compiled version of it you may make.   |
//--------------------------------------------------------------------------'

using DPTechnology.AnnexLibraries;
using DPTechnology.AnnexLibraries.EspritAnnex;
using Microsoft.Win32;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Linq;
using System.Net.Http;
using System.Net;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;
using System.Threading.Tasks;
using System.Windows.Forms;
using DentalAddin;
using Esprit;
using Acrodent.EspritAddIns.ESPRIT2025AddinProject.DentalAddinCompat;
using Acrodent.EspritAddIns.ESPRIT2025AddinProject; // PatientContext
using DrawingPoint = System.Drawing.Point;
using EspritConstants;
using EspritTechnology;
using EspritGeometry;
using System.Diagnostics;
using WinFormsButton = System.Windows.Forms.Button;

namespace Acrodent.EspritAddIns.ESPRIT2025AddinProject
{

    [ClassInterface(ClassInterfaceType.None), ComVisible(true),
        Guid("1c4198bd-2143-470a-a041-93f2ebf4c904"),
        ProgId("ESPRIT2025AddinProject.Connect")]
    public class Connect : DPTechnology.AnnexLibraries.EspritAddIn
    {
        private static readonly HttpClient MetaHttp;

        static Connect()
        {
            var handler = new HttpClientHandler
            {
                AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate,
                UseProxy = false
            };
            MetaHttp = new HttpClient(handler)
            {
                Timeout = TimeSpan.FromSeconds(10)
            };
        }

        // Default Property Procedures should not need changes
        #region " Default Property Procedures "

        private DPTechnology.AnnexLibraries.IConnectionManager _ConnectionManager;
        protected override DPTechnology.AnnexLibraries.IConnectionManager ConnectionManager
        {
            get
            {
                if (_ConnectionManager == null)
                {
                    _ConnectionManager = new DPTechnology.AnnexLibraries.EspritAnnex.ConnectionManager();
                    _ConnectionManager.AddInConnect += _ConnectionManager_AddInConnect;
                    _ConnectionManager.AddInDisconnect += _ConnectionManager_AddInDisconnect;
                    _ConnectionManager.DocumentClosed += _ConnectionManager_DocumentClosed;
                    _ConnectionManager.DocumentInitialize += _ConnectionManager_DocumentInitialize;
                    _ConnectionManager.EspritApplicationShutdown += _ConnectionManager_EspritApplicationShutdown;
                }
                return _ConnectionManager;
            }
        }

        // requestId 추출: "requestId.xxx" 접두사 활용
        private static string ExtractRequestId(string fileName)
        {
            if (string.IsNullOrWhiteSpace(fileName)) return null;
            // ".filled.stl" 제거 후 전체 접두사를 requestId로 사용
            var baseName = Path.GetFileNameWithoutExtension(fileName);
            if (string.IsNullOrWhiteSpace(baseName)) return null;
            if (baseName.EndsWith(".filled", StringComparison.OrdinalIgnoreCase))
            {
                baseName = baseName.Substring(0, baseName.Length - ".filled".Length);
            }
            // DB 포맷: YYYYMMDD-<토큰> 형태에 맞춰 앞 2세그먼트만 사용
            var parts = baseName.Split('-');
            if (parts.Length >= 2)
            {
                return $"{parts[0]}-{parts[1]}";
            }
            return baseName;
        }

        // 백엔드 메타 조회 후 PatientContext 채우기
        private static async Task FetchAndSetPatientContextAsync(string requestId, Action<string> log)
        {
            string baseUrl = ProcessConfig.BackendUrl;
            baseUrl = baseUrl.TrimEnd('/');
            string url = $"{baseUrl}/bg/request-meta?requestId={Uri.EscapeDataString(requestId)}";

            // TLS 강제 (DNS/인증 오류 감소)
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

            var client = MetaHttp;
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Add("Accept", "application/json");
            var bridgeSecret = ProcessConfig.BridgeSharedSecret;
            if (!string.IsNullOrWhiteSpace(bridgeSecret))
            {
                client.DefaultRequestHeaders.Add("X-Bridge-Secret", bridgeSecret);
            }
            log?.Invoke($"[Addin] request-meta GET {url} (X-Bridge-Secret set={(!string.IsNullOrWhiteSpace(bridgeSecret))})");
            HttpResponseMessage resp;
            try
            {
                resp = await client.GetAsync(url).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                var msg = $"request-meta HTTP error: {ex.GetType().Name} {ex.Message}";
                log?.Invoke($"[Addin] {msg}");
                return;
            }
            if (!resp.IsSuccessStatusCode)
            {
                string body = "";
                try { body = await resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { }
                var msg = $"request-meta failed status={resp.StatusCode} body={body}";
                log?.Invoke($"[Addin] {msg}");
                return;
            }
            var stream = await resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
            var serializer = new DataContractJsonSerializer(typeof(RequestMetaResponse));
            var meta = serializer.ReadObject(stream) as RequestMetaResponse;
            if (meta == null || meta.data == null || meta.data.caseInfos == null)
            {
                var msg = "request-meta parse failed or empty";
                log?.Invoke($"[Addin] {msg}");
                return;
            }

            var ci = meta.data.caseInfos;
            var req = new NcGenerationRequest
            {
                MaxDiameter = ci.maxDiameter,
                ConnectionDiameter = ci.connectionDiameter,
                WorkType = ci.workType,
                LotNumber = ci.lotNumber,
                // NumData/NumCombobox는 응답에 없으므로 그대로 둔다
            };
            log?.Invoke($"[Addin] request-meta data -> Clinic={ci.clinicName}, Patient={ci.patientName}, Tooth={ci.tooth}, Implant={ci.implantManufacturer}/{ci.implantSystem}/{ci.implantType}, MaxDiameter={ci.maxDiameter:F2}, ConnectionDiameter={ci.connectionDiameter:F2}, WorkType={ci.workType}, Lot={ci.lotNumber}");
            PatientContext.SetFromRequest(req);
            log?.Invoke($"[Addin] request-meta loaded: MaxDiameter={ci.maxDiameter:F2}, ConnectionDiameter={ci.connectionDiameter:F2}, WorkType={ci.workType}");
        }

        [DataContract]
        private class RequestMetaResponse
        {
            [DataMember] public bool ok { get; set; }
            [DataMember] public RequestMetaData data { get; set; }
        }

        [DataContract]
        private class RequestMetaData
        {
            [DataMember] public string requestId { get; set; }
            [DataMember] public CaseInfos caseInfos { get; set; }
        }

        [DataContract]
        private class CaseInfos
        {
            [DataMember] public string clinicName { get; set; }
            [DataMember] public string patientName { get; set; }
            [DataMember] public string tooth { get; set; }
            [DataMember] public string implantManufacturer { get; set; }
            [DataMember] public string implantSystem { get; set; }
            [DataMember] public string implantType { get; set; }
            [DataMember] public double maxDiameter { get; set; }
            [DataMember] public double connectionDiameter { get; set; }
            [DataMember] public string workType { get; set; }
            [DataMember] public string lotNumber { get; set; }
        }

        // 배열 로깅 유틸
        private static string FormatArray<T>(IEnumerable<T> arr)
        {
            if (arr == null) return "null";
            return "[" + string.Join(",", arr) + "]";
        }

        private sealed class AddInRunningForm : Form
        {
            private readonly Label _label;

            public AddInRunningForm(string message)
            {
                FormBorderStyle = FormBorderStyle.FixedToolWindow;
                StartPosition = FormStartPosition.Manual;
                TopMost = true;
                ShowInTaskbar = false;
                Text = "Abuts.fit Add-in";
                Size = new Size(320, 96);

                _label = new Label
                {
                    Dock = DockStyle.Fill,
                    TextAlign = ContentAlignment.MiddleLeft,
                    Font = new Font("Segoe UI", 10, FontStyle.Bold),
                    Padding = new Padding(16),
                    Text = message
                };

                Controls.Add(_label);

                var screen = Screen.PrimaryScreen?.WorkingArea ?? new Rectangle(0, 0, 800, 600);
                Location = new DrawingPoint(screen.Right - Width - 20, screen.Bottom - Height - 160);
            }

            public void UpdateMessage(string message)
            {
                _label.Text = message;
            }
        }

        private void ShowRunningIndicator()
        {
            try
            {
                var message = "[Abuts.fit Add-in] 실행 중";

                if (_runningForm == null || _runningForm.IsDisposed)
                {
                    _runningForm = new AddInRunningForm(message);
                }
                else
                {
                    _runningForm.UpdateMessage(message);
                }

                if (!_runningForm.Visible)
                {
                    _runningForm.Show();
                }

                _runningForm.BringToFront();
            }
            catch
            {
                // ignore
            }
        }

        private void HideRunningIndicator()
        {
            try
            {
                if (_runningForm != null && !_runningForm.IsDisposed)
                {
                    _runningForm.Close();
                    _runningForm.Dispose();
                    _runningForm = null;
                }
            }
            catch
            {
                // ignore
            }
        }

        private sealed class AddInStatusForm : Form
        {
            private readonly Label _statusLabel;
            private readonly ListBox _listBox;
            private readonly WinFormsButton _prevButton;
            private readonly WinFormsButton _nextButton;
            private readonly Label _pageLabel;
            private readonly Func<Document> _getDocument;
            private readonly Func<string> _getDirectory;
            private readonly Action<string> _log;
            private List<string> _files = new List<string>();
            private int _pageIndex;
            private const int PageSize = 5;
            private const int HeaderHeight = 36;      // 높이 축소
            private const int ListVisibleCount = 3;   // 리스트 표시 줄수 축소

            public AddInStatusForm(Func<Document> getDocument, Func<string> getDirectory, Action<string> logAction)
            {
                _getDocument = getDocument ?? throw new ArgumentNullException(nameof(getDocument));
                _getDirectory = getDirectory ?? throw new ArgumentNullException(nameof(getDirectory));
                _log = logAction;

                FormBorderStyle = FormBorderStyle.FixedToolWindow;
                StartPosition = FormStartPosition.Manual;
                TopMost = true;
                ShowInTaskbar = false;
                Text = "Abuts.fit Add-in";

                // 상단 라벨 제거, 리스트가 상단부터 덮도록 배치
                _statusLabel = new Label
                {
                    Visible = false,
                    Height = 0
                };

                _listBox = new ListBox
                {
                    Dock = DockStyle.Fill,
                    IntegralHeight = true,
                    Font = new Font("Segoe UI", 9, FontStyle.Regular)
                };
                var listHeight = (_listBox.ItemHeight * ListVisibleCount) + 8;
                _listBox.Height = listHeight;
                _listBox.Click += (_, _) => MergeSelected();

                var bottomPanel = new Panel
                {
                    Dock = DockStyle.Bottom,
                    Height = 32,
                    Padding = new Padding(8, 2, 8, 2)
                };

                _prevButton = new WinFormsButton
                {
                    Text = "이전",
                    Width = 60,
                    Height = 26,
                    Left = 8,
                    Top = 4
                };
                _prevButton.Click += (_, _) => ChangePage(_pageIndex - 1);

                _nextButton = new WinFormsButton
                {
                    Text = "다음",
                    Width = 60,
                    Height = 26,
                    Left = 76,
                    Top = 6
                };
                _nextButton.Click += (_, _) => ChangePage(_pageIndex + 1);

                _pageLabel = new Label
                {
                    AutoSize = true,
                    Top = 10,
                    Left = 148,
                    ForeColor = Color.DimGray
                };

                bottomPanel.Controls.Add(_prevButton);
                bottomPanel.Controls.Add(_nextButton);
                bottomPanel.Controls.Add(_pageLabel);

                Controls.Add(_listBox);
                Controls.Add(bottomPanel);

                // 메인 창 높이를 리스트 5개 기준으로 최소화
                var desiredHeight = HeaderHeight + listHeight + bottomPanel.Height + 24; // chrome padding 보정 축소
                Size = new Size(320, desiredHeight);

                var screen = Screen.PrimaryScreen?.WorkingArea ?? new Rectangle(0, 0, 800, 600);
                Location = new DrawingPoint(screen.Right - Width - 20, screen.Bottom - Height - 20);
            }

            public void UpdateStatus(string message)
            {
                // 메시지창(상태 패널)에는 로그를 표시하지 않고 고정 제목만 유지
                _statusLabel.Text = "Abuts.fit Add-in";
            }

            public void RefreshFiles()
            {
                try
                {
                    var dir = _getDirectory();
                    if (!Directory.Exists(dir))
                    {
                        Directory.CreateDirectory(dir);
                    }

                    _files = Directory.GetFiles(dir, "*.filled.stl")
                        .OrderByDescending(File.GetLastWriteTime)
                        .ToList();
                    _pageIndex = 0;
                    RenderPage();
                }
                catch (Exception ex)
                {
                    MessageBox.Show($"Filled STL 목록을 불러올 수 없습니다: {ex.Message}", "오류", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }

            private void RenderPage()
            {
                _listBox.Items.Clear();

                if (_files.Count == 0)
                {
                    _listBox.Items.Add("파일이 없습니다.");
                    _prevButton.Enabled = false;
                    _nextButton.Enabled = false;
                    _pageLabel.Text = "0개";
                    return;
                }

                var pageItems = _files.Skip(_pageIndex * PageSize).Take(PageSize).ToList();
                foreach (var f in pageItems)
                {
                    var fi = new FileInfo(f);
                    _listBox.Items.Add($"{fi.Name} (수정: {fi.LastWriteTime:MM-dd HH:mm})");
                }

                _prevButton.Enabled = _pageIndex > 0;
                _nextButton.Enabled = (_pageIndex + 1) * PageSize < _files.Count;
                _pageLabel.Text = $"{_pageIndex + 1} / {Math.Max(1, (int)Math.Ceiling(_files.Count / (double)PageSize))} ({_files.Count}개)";
            }

            private void ChangePage(int newPage)
            {
                if (newPage < 0) return;
                if (newPage * PageSize >= _files.Count) return;
                _pageIndex = newPage;
                RenderPage();
            }

            private async void MergeSelected()
            {
                if (_files.Count == 0) return;
                var selectedIndex = _listBox.SelectedIndex;
                if (selectedIndex < 0) return;

                var fullIndex = _pageIndex * PageSize + selectedIndex;
                if (fullIndex < 0 || fullIndex >= _files.Count) return;

                var targetPath = _files[fullIndex];
                var fileNameOnly = Path.GetFileName(targetPath);
                var doc = _getDocument?.Invoke();
                if (doc == null)
                {
                    MessageBox.Show("현재 열린 ESPRIT 문서를 찾을 수 없습니다.", "오류", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    return;
                }

                try
                {
                    _log?.Invoke($"[Addin] Processing start (deferred merge): {Path.GetFileName(targetPath)}");
                    // requestId 추출 및 메타 조회
                    string requestId = ExtractRequestId(fileNameOnly);
                    if (!string.IsNullOrEmpty(requestId))
                    {
                        try
                        {
                            _log?.Invoke($"[Addin] Fetching request meta for requestId={requestId}");
                            await FetchAndSetPatientContextAsync(requestId, _log);
                        }
                        catch (Exception ex)
                        {
                            _log?.Invoke($"[Addin] Meta fetch failed: {ex.Message}");
                        }
                    }
                    else
                    {
                        _log?.Invoke("[Addin] requestId를 파일명에서 추출하지 못했습니다. PatientContext는 기존값 유지.");
                    }

                    _log?.Invoke($"[Addin] PatientContext NumData={FormatArray(PatientContext.NumData)} NumCombobox={FormatArray(PatientContext.NumCombobox)} MaxDiameter={PatientContext.MaxDiameter:F2} ConnectionDiameter={PatientContext.ConnectionDiameter:F2} WorkType={PatientContext.WorkType}");

                    // Trace -> _log 출력용 리스너 연결
                    var traceListener = new LogTraceListener(msg => _log?.Invoke(msg));
                    System.Diagnostics.Trace.Listeners.Add(traceListener);
                    if (_espApp != null)
                    {
                        try
                        {
                            _log?.Invoke("[Addin] DentalPipeline 실행 시작");
                            MainModule.Bind(_espApp, doc);
                            // STL은 MainModule에서 템플릿 오픈 후 병합
                            MainModule.ProcessStlFile(targetPath);
                            _log?.Invoke("[Addin] DentalPipeline 완료");
                        }
                        catch (Exception ex)
                        {
                            System.Diagnostics.Trace.WriteLine($"Connect: DentalPipeline failed - {ex.Message}");
                            _log?.Invoke($"[Addin] DentalPipeline 실패: {ex.Message}");
                        }
                    }
                    System.Diagnostics.Trace.Listeners.Remove(traceListener);
                }
                catch (Exception ex)
                {
                    MessageBox.Show($"병합 실패: {ex.Message}", "오류", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }

        // Trace → _log 연결용 리스너
        private sealed class LogTraceListener : TraceListener
        {
            private readonly Action<string> _forward;
            public LogTraceListener(Action<string> forward) => _forward = forward;
            public override void Write(string message) => _forward?.Invoke(message);
            public override void WriteLine(string message) => _forward?.Invoke(message);
        }

        private void ShowStatusPanel(string message)
        {
            try
            {
                if (_statusForm == null || _statusForm.IsDisposed)
                {
                    _statusForm = new AddInStatusForm(() => _espApp?.Document, ResolveFilledDirectory, LogToEspritOutputs);
                }

                _statusForm.UpdateStatus(message);
                _statusForm.RefreshFiles();
                if (!_statusForm.Visible)
                {
                    _statusForm.Show();
                }

                _statusForm.BringToFront();
            }
            catch (Exception ex)
            {
                System.Diagnostics.Trace.WriteLine($"Connect: ShowStatusPanel failed - {ex.Message}");
            }
        }

        private void HideStatusPanel()
        {
            try
            {
                if (_statusForm != null && !_statusForm.IsDisposed)
                {
                    _statusForm.Close();
                    _statusForm.Dispose();
                    _statusForm = null;
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Trace.WriteLine($"Connect: HideStatusPanel failed - {ex.Message}");
            }
        }

        private static void AutoFocusDocument(Document doc)
        {
            try
            {
                var window = GetProp(doc, "Windows");
                var activeWindow = GetProp(window, "ActiveWindow") ?? window;
                if (activeWindow == null)
                {
                    return;
                }

                // Zoom fit/all (window + document) + explicit Zoom scale
                TryInvokeMethod(activeWindow, "ZoomFit");
                TryInvokeMethod(activeWindow, "ZoomAll");
                TryInvokeMethod(activeWindow, "ZoomExtents");
                TryInvokeMethod(doc, "ZoomAll");
                TryInvokeMethod(doc, "ZoomFit");
                TryInvokeMethod(activeWindow, "Zoom", 1.2);

                // Set view plane to YZ/ZY if available
                var view = GetProp(activeWindow, "View") ?? GetProp(doc, "ActiveView");
                var planeType = ResolveViewPlaneType();
                if (planeType != null && view != null)
                {
                    object yz = null;
                    try { yz = Enum.Parse(planeType, "espViewPlaneYZ"); } catch { }
                    if (yz != null)
                    {
                        TrySetProperty(view, "Plane", yz);
                        TryInvokeMethod(view, "SetViewPlane", yz);
                        TryInvokeMethod(view, "Refresh");
                    }
                }

                TryInvokeMethod(doc, "UpdateView");
                TryInvokeMethod(doc, "Refresh");
                TryInvokeMethod(activeWindow, "Refresh");
            }
            catch
            {
                // ignore focus errors
            }
        }

        private static Type ResolveViewPlaneType()
        {
            // Attempt to load enum EspritConstants.espViewPlane without referencing namespace as a type
            var type = Type.GetType("EspritConstants.espViewPlane");
            if (type != null) return type;

            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    type = asm.GetType("EspritConstants.espViewPlane");
                    if (type != null) return type;
                }
                catch { /* ignore */ }
            }

            return null;
        }

        private static object GetProp(object target, string name)
        {
            if (target == null || string.IsNullOrEmpty(name)) return null;
            try
            {
                var p = target.GetType().GetProperty(name, BindingFlags.Public | BindingFlags.Instance);
                return p?.GetValue(target);
            }
            catch { return null; }
        }

        private static void TrySetProperty(object target, string name, object value)
        {
            if (target == null || string.IsNullOrEmpty(name)) return;
            try
            {
                var p = target.GetType().GetProperty(name, BindingFlags.Public | BindingFlags.Instance);
                if (p != null && p.CanWrite)
                {
                    p.SetValue(target, value);
                }
            }
            catch
            {
                // ignore
            }
        }

        private static void TryInvokeMethod(object target, string methodName, params object[] args)
        {
            if (target == null || string.IsNullOrEmpty(methodName)) return;
            try
            {
                var types = args?.Select(a => a?.GetType() ?? typeof(object)).ToArray() ?? Type.EmptyTypes;
                var method = target.GetType().GetMethod(methodName, BindingFlags.Public | BindingFlags.Instance);
                method?.Invoke(target, args);
            }
            catch
            {
                // ignore
            }
        }

        private static EspritMenus.Menu FindToolbarsSubMenu(EspritMenus.Menus rootMenus)
        {
            if (rootMenus == null)
            {
                return null;
            }

            EspritMenus.Menu viewMenu = FindTopMenu(rootMenus, new string[4] { "&View", "보기(&V)", "视图(&V)", "ビュー(&V)" });
            if (viewMenu == null)
            {
                return null;
            }

            int count = viewMenu.Count;
            for (int i = 1; i <= count; i++)
            {
                EspritMenus.MenuItem item = viewMenu[i];
                if (item == null)
                {
                    continue;
                }

                string name = item.Name;
                if (name == "&工具栏..." || name == "&Toolbars..." || name == "툴바(&T)" || name == "ツールバー(&T)...")
                {
                    return item.SubMenu;
                }
            }

            return null;
        }

        private static EspritMenus.Menu FindTopMenu(EspritMenus.Menus rootMenus, string[] candidates)
        {
            if (rootMenus == null || candidates == null)
            {
                return null;
            }

            foreach (string candidate in candidates)
            {
                if (string.IsNullOrEmpty(candidate))
                {
                    continue;
                }

                try
                {
                    EspritMenus.Menu menu = rootMenus[candidate];
                    if (menu != null)
                    {
                        return menu;
                    }
                }
                catch
                {
                    // ignore
                }
            }

            // fallback: some installs only support ordinal indices
            try
            {
                for (int i = 1; i <= rootMenus.Count; i++)
                {
                    EspritMenus.Menu menu = rootMenus[i];
                    if (menu == null)
                    {
                        continue;
                    }

                    foreach (string candidate in candidates)
                    {
                        if (!string.IsNullOrEmpty(candidate) && menu.Name == candidate)
                        {
                            return menu;
                        }
                    }
                }
            }
            catch
            {
                // ignore
            }

            return null;
        }

        private static void SafeRemoveMenuItem(EspritMenus.Menu menu, string name)
        {
            if (menu == null || string.IsNullOrEmpty(name))
            {
                return;
            }

            try
            {
                menu.Remove(name);
            }
            catch
            {
                // ignore
            }
        }

        private static void EnsureMenuSeparator(EspritMenus.Menu menu)
        {
            if (menu == null)
            {
                return;
            }

            try
            {
                if (menu.Count > 0 && menu[menu.Count].Type != EspritConstants.espMenuItemType.espMenuItemSeparator)
                {
                    menu.Add(EspritConstants.espMenuItemType.espMenuItemSeparator);
                }
            }
            catch
            {
                // ignore
            }
        }

        private static void RemoveTrailingSeparators(EspritMenus.Menu menu)
        {
            if (menu == null)
            {
                return;
            }

            try
            {
                while (menu.Count > 0 && menu[menu.Count].Type == EspritConstants.espMenuItemType.espMenuItemSeparator)
                {
                    menu.Remove(menu.Count);
                }
            }
            catch
            {
                // ignore
            }
        }

        public override string Description => Properties.Resources.AddInDescription;

        public override string FriendlyName => Properties.Resources.AddInFriendlyName;

        public override string Name => System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;

        public override System.Diagnostics.TraceLevel OutputWindowTraceLevel => Properties.Settings.Default.OutputWindowTraceLevel;

        protected override Nullable<Int32> PreviousLanguage
        {
            get
            {
                Int32 returnValue;
                if (Int32.TryParse(Properties.Settings.Default.PreviousLanguage, out returnValue))
                    { return returnValue; }
                else
                    { return null; }
            }
            set
            {
                if (value.HasValue)
                {
                    Properties.Settings.Default.PreviousLanguage = value.Value.ToString();
                    Properties.Settings.Default.Save();
                }
            }
        }

        protected override System.Globalization.CultureInfo ResourcesCulture
        {
            get { return Properties.Resources.Culture; }
            set { Properties.Resources.Culture = value; }
        }

        #endregion

        private const string regSettings = "Settings:";
        private const string regPositionDock = "Dock";
        private const string regPositionTop = "Top";
        private const string regPositionLeft = "Left";
        private const string regPositionWidth = "Width";
        private const string regPositionHeight = "Height";

        public static Esprit.Application _espApp;
        public static Esprit.Application EspritApp => _espApp;
        public new static Esprit.Document Document => _espApp?.Document;

        public EspritMenus.Menu _tbMenu = default(EspritMenus.Menu);
        public EspritMenus.MenuItem _tbMenuItem = default(EspritMenus.MenuItem);

        public List<int> _iCNumbs = new List<int>();
        private const string ToolbarDisplayName = "abuts.fit";
        private const string ToolbarInternalName = "abutsfit_Addin_";
        private bool _toolbarPositionLoaded = false;

        public static int _iCntOfCommands = 1;
        public Esprit.PMTab exTab;
        public Esprit.ProjectManager _pm;
        public static int _MyCookie;

        internal static DentalAddinHost DentalHost { get; } = new DentalAddinHost();

        private Esprit.ToolBar _toolbar;
        private RepeatProcess _repeatProcess;
        private AddInRunningForm _runningForm;
        private AddInStatusForm _statusForm;
        private readonly string _debugLogPath = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "AbutsFit", "addin.log");
        private const int HeartbeatIntervalMs = 60 * 1000;
        private FilledStlBrowserForm _filledBrowser;

        public void _ConnectionManager_AddInConnect(Esprit.Application espritApplication)
        {
            _espApp = espritApplication;
            _pm = _espApp.ProjectManager;
            DentalHost.Initialize(_espApp);
            DentalHost.SetDocumentResolver(() => _espApp?.Document);

            // 서버 자동 시작
            if (_repeatProcess == null)
            {
                try
                {
                    _repeatProcess = new RepeatProcess(_espApp);
                    _repeatProcess.Run();
                }
                catch (Exception ex)
                {
                    LogToEspritOutputs($"[Addin] Failed to auto-start RepeatProcess: {ex.Message}");
                }
            }

            // -------------------------
            // 1. Apply commands
            // -------------------------
            var EC = espritApplication.AddIn as EspritCommands.AddIn;
            _MyCookie = EC.GetCookie();

            try
            {
                _espApp.ToolBars.Remove(ToolbarInternalName);
            }
            catch
            {
                // ignore
            }

            _toolbar = _espApp.ToolBars.Add(ToolbarInternalName);
            var toolbarIcons = EnsureToolbarIcons();
            for (int i = 0; i < _iCntOfCommands; i++)
            {
                _iCNumbs.Add(EC.AddCommand(_MyCookie, i, "abuts.fit"));
            }

            for (int i = 0; i < _iCntOfCommands; i++)
            {
                Esprit.ToolBarControl tbcon = _toolbar.Add(EspritConstants.espToolBarControl.espToolBarControlButton, ToolbarInternalName + i, _iCNumbs[i]);
                tbcon.SetBitmap(toolbarIcons.smallIconPath, toolbarIcons.largeIconPath);
                tbcon.Enabled = true;
                tbcon.Name = ToolbarDisplayName;
            }

            //EC.OnCommand;
            EC.OnCommand += EC_OnCommand;

            // -------------------------
            // 2. Commands on View menu
            // -------------------------

            try
            {
                EspritMenus.Menus myMenu = _espApp.Menus as EspritMenus.Menus;
                EspritMenus.Menu toolbarsSubMenu = FindToolbarsSubMenu(myMenu);
                if (toolbarsSubMenu != null)
                {
                    SafeRemoveMenuItem(toolbarsSubMenu, ToolbarDisplayName);
                    EnsureMenuSeparator(toolbarsSubMenu);
                    _tbMenuItem = toolbarsSubMenu.Add(EspritConstants.espMenuItemType.espMenuItemCommand, ToolbarDisplayName, _iCNumbs[0]);
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Trace.WriteLine("Connect: View/Toolbars menu hook failed: " + ex);
            }

            // -------------------------
            // 3. Commands on Tool sub menu
            // -------------------------

            try
            {
                EspritMenus.Menus myMenu = _espApp.Menus as EspritMenus.Menus;
                EspritMenus.Menu toolsMenu = FindTopMenu(myMenu, new string[3] { "&Tools", "도구(&T)", "工具(&T)" });
                if (toolsMenu != null)
                {
                    SafeRemoveMenuItem(toolsMenu, ToolbarDisplayName);
                    RemoveTrailingSeparators(toolsMenu);
                    toolsMenu.Add(EspritConstants.espMenuItemType.espMenuItemSeparator);
                    toolsMenu.Add(EspritConstants.espMenuItemType.espMenuItemPopUp, ToolbarDisplayName);

                    EspritMenus.Menu popupSubMenu = null;
                    try
                    {
                        popupSubMenu = toolsMenu[ToolbarDisplayName].SubMenu;
                    }
                    catch
                    {
                        popupSubMenu = null;
                    }

                    if (popupSubMenu != null)
                    {
                        popupSubMenu.Add(EspritConstants.espMenuItemType.espMenuItemCommand, "abuts.fit", _iCNumbs[0]);
                    }
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Trace.WriteLine("Connect: Tools menu hook failed: " + ex);
            }

            // Ensure toolbar position is applied after toolbar/menu creation.
            // This makes sure position loading occurs after the application has initialized UI elements.
            try
            {
                if (!_toolbarPositionLoaded && _toolbar != null)
                {
                    Toolbar_PositionLoad(ToolbarInternalName, _toolbar);
                    _toolbarPositionLoaded = true;
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Trace.WriteLine($"Connect: Failed to load toolbar position in AddInConnect: {ex}");
            }

            ShowDefaultStatusPanel();
            // Heartbeat disabled
        }


        private void EC_OnCommand(int Cookie, int UserId)
        {
            if (Cookie != _MyCookie)
                return;

            switch (UserId)
            {
                case 0:
                    ShowDefaultStatusPanel();

                    if (_repeatProcess == null)
                    {
                        _repeatProcess = new RepeatProcess(_espApp);
                        _repeatProcess.Run();
                    }

                    break;
            }
        }

        private void ShowDefaultStatusPanel()
        {
            try
            {
                var message = BuildFilledStatusMessage();
                ShowStatusPanel(message);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Trace.WriteLine($"Connect: ShowDefaultStatusPanel failed - {ex.Message}");
            }
        }

        private void ShowFilledBrowser()
        {
            try
            {
                var directory = ResolveFilledDirectory();
                if (_filledBrowser == null || _filledBrowser.IsDisposed)
                {
                    _filledBrowser = new FilledStlBrowserForm(directory, () => _espApp?.Document);
                }

                _filledBrowser.RefreshFiles();
                _filledBrowser.Show();
                _filledBrowser.BringToFront();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Filled STL Browser를 열 수 없습니다: {ex.Message}", "오류", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private static string ResolveFilledDirectory()
        {
            // 절대 경로 우선
            var absolute = @"C:\abuts.fit\bg\storage\2-filled";
            if (Directory.Exists(absolute))
            {
                return absolute;
            }

            // 기존 탐색 로직 (개발 환경 대비)
            var candidate = TryResolveStoragePath("2-filled");
            if (candidate != null)
            {
                return candidate;
            }

            // Fallback to 이전 상대 경로 추정
            var baseDir = AppDomain.CurrentDomain.BaseDirectory;
            var currentData = DentalHost.CurrentData; // NumData, NumCombobox 등
            return Path.GetFullPath(Path.Combine(baseDir, "..", "..", "storage", "2-filled"));
        }

        private static string TryResolveStoragePath(string subFolder)
        {
            var baseDir = AppDomain.CurrentDomain.BaseDirectory;
            var currentData = DentalHost.CurrentData; // NumData, NumCombobox 등
            var dir = new DirectoryInfo(baseDir);

            for (int i = 0; i < 6 && dir != null; i++)
            {
                var candidate = Path.Combine(dir.FullName, "storage", subFolder);
                if (Directory.Exists(candidate))
                {
                    return candidate;
                }
                dir = dir.Parent;
            }

            return null;
        }

        private string BuildFilledStatusMessage()
        {
            var timestamp = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
            try
            {
                var dir = ResolveFilledDirectory();
                if (!Directory.Exists(dir))
                {
                    Directory.CreateDirectory(dir);
                }

                var files = Directory.GetFiles(dir, "*.filled.stl")
                    .OrderByDescending(File.GetLastWriteTime)
                    .Take(5)
                    .ToList();

                if (files.Count == 0)
                {
                    return $"[{timestamp}] Abuts.fit Add-in\nFilled STL: 파일이 없습니다.";
                }

                var lines = files
                    .Select(f =>
                    {
                        var fi = new FileInfo(f);
                        return $"- {fi.Name} (수정: {fi.LastWriteTime:MM-dd HH:mm})";
                    });

                return $"[{timestamp}] Abuts.fit Add-in\nFilled STL 최근 5개:\n{string.Join("\n", lines)}";
            }
            catch (Exception ex)
            {
                System.Diagnostics.Trace.WriteLine($"Connect: BuildFilledStatusMessage failed - {ex.Message}");
                return $"[{timestamp}] Abuts.fit Add-in\nFilled STL 목록을 불러오지 못했습니다.";
            }
        }

        public void _ConnectionManager_AddInDisconnect()
        {
            // Triggered when the Add-In disconnects because it was Unloaded from the Add-In Manager.
            // This means ESPRIT will remain running; otherwise only EspritApplicationShutdown is triggered.
            // This event procedure can be removed if it does not need to be used.
            if (exTab != null)
            {
                try
                {
                    _pm?.PMTabs?.Remove(exTab.HWND);
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Trace.WriteLine($"Connect: PMTab remove failed - {ex.Message}");
                }
                exTab = null;
            }

            if (_repeatProcess != null)
            {
                _repeatProcess.Dispose();
                _repeatProcess = null;
            }

            HideStatusPanel();
            HideRunningIndicator();
            // Heartbeat disabled
        }

        public void _ConnectionManager_DocumentClosed(bool espritIsShuttingDown)
        {
            // Triggered after the Document has been closed.
            // The Boolean argument signals whether or not the Document was closed because ESPRIT is shutting down.
            // This event procedure can be removed if it does not need to be used.
        }

        public void _ConnectionManager_DocumentInitialize(Esprit.Document espritDocument, string fileName)
        {
            // Triggered whenever the Document object has been re-initialized.
            //
            // If an Esprit.Document object property or variable is declared in your project you can assign it from here.
            // Procedures that apply to both New and existing ESPRIT files can then be called here also.
            //
            // Note that a Null filename (Nothing) indicates a New Document (AfterNewDocumentOpen event),
            // while a non-null filename could be an existing file (AfterDocumentOpen or AfterTemplateOpen event),
            // or could indicate connection to a running Esprit.Application that had a Document already open.
            // In the latter case the filename will not be null, but could be Empty to indicate an unsaved Document.
            //
            if (fileName == null) { return; }
            // Procedures that apply only when opening existing files (and not staring New ones) can be called here.
            //
            // This event procedure can be removed if it does not need to be used (but that is rarely the case).

            // Call toolbar position load only if it has not already been applied.
            if (!_toolbarPositionLoaded && _toolbar != null)
            {
                try
                {
                    Toolbar_PositionLoad(ToolbarInternalName, _toolbar);
                    _toolbarPositionLoaded = true;
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Trace.WriteLine($"Connect: Failed to load toolbar position in DocumentInitialize: {ex}");
                }
            }
        }

        public void _ConnectionManager_EspritApplicationShutdown()
        {
            // Triggered when the Add-In disconnects explicitly because ESPRIT is shutting down.
            // This event can be removed if it does not need to be used.
            Toolbar_PositionSave(ToolbarInternalName, _toolbar);
            
            if (_repeatProcess != null)
            {
                _repeatProcess.Dispose();
                _repeatProcess = null;
            }

            HideRunningIndicator();
            StopHeartbeat();
        }

        #region TOOLBAR_POSITION
        private void Toolbar_PositionSave(string aToolbarName, Esprit.ToolBar aToolbarObject)
        {
            if (aToolbarObject == null) return;
            WriteReg(regPositionDock, aToolbarObject.Position.ToString());
            WriteReg(regPositionTop, aToolbarObject.Top.ToString());
            WriteReg(regPositionLeft, aToolbarObject.Left.ToString());
            WriteReg(regPositionWidth, aToolbarObject.Width.ToString());
            WriteReg(regPositionHeight, aToolbarObject.Height.ToString());
        }

        private void Toolbar_PositionLoad(string aToolbarName, Esprit.ToolBar aToolbarObject)
        {

            string pos = ReadReg(regPositionDock);
            switch (pos)
            {
                case "espToolBarPositionFloating":
                    {
                        //aToolbarObject.Dock(EspritConstants.espToolBarPosition.espToolBarPositionFloating);
                        break;
                    }
                case "espToolBarPositionTop":
                    {
                        aToolbarObject.Dock(EspritConstants.espToolBarPosition.espToolBarPositionTop);
                        break;
                    }
                case "espToolBarPositionLeft":
                    {
                        aToolbarObject.Dock(EspritConstants.espToolBarPosition.espToolBarPositionLeft);
                        break;
                    }
                case "espToolBarPositionBottom":
                    {
                        aToolbarObject.Dock(EspritConstants.espToolBarPosition.espToolBarPositionBottom);
                        break;
                    }
                case "espToolBarPositionRight":
                    {
                        aToolbarObject.Dock(EspritConstants.espToolBarPosition.espToolBarPositionRight);
                        break;
                    }
            }
            //aToolbarObject.Dock(EspritConstants.espToolBarPosition.espToolBarPositionFloating);
            switch (aToolbarObject.Position)
            {
                case EspritConstants.espToolBarPosition.espToolBarPositionBottom:
                    {
                        aToolbarObject.Top = Convert.ToInt32(ReadReg(regPositionTop)) + aToolbarObject.Height;
                        aToolbarObject.Left = Convert.ToInt32(ReadReg(regPositionLeft));
                        break;
                    }
                case EspritConstants.espToolBarPosition.espToolBarPositionLeft:
                    {
                        aToolbarObject.Top = Convert.ToInt32(ReadReg(regPositionTop));
                        aToolbarObject.Left = Convert.ToInt32(ReadReg(regPositionLeft)) + aToolbarObject.Width;
                        break;
                    }
                case EspritConstants.espToolBarPosition.espToolBarPositionRight:
                    {
                        aToolbarObject.Top = Convert.ToInt32(ReadReg(regPositionTop));
                        aToolbarObject.Left = Convert.ToInt32(ReadReg(regPositionLeft));
                        break;
                    }
                case EspritConstants.espToolBarPosition.espToolBarPositionTop:
                    {
                        aToolbarObject.Top = Convert.ToInt32(ReadReg(regPositionTop));
                        aToolbarObject.Left = Convert.ToInt32(ReadReg(regPositionLeft));
                        break;
                    }
            }
        }
        #endregion TOOLBAR_POSITION

        #region Registry_Read_Write
        private string ReadReg(string valueName)
        {
            const string userRoot = "HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\D.P.Technology\\ESPRIT\\AddIns";
            const string subkey = "ESPRIT2025AddinProject.Connect\\" + regSettings + ToolbarInternalName + ".ToolBar";
            const string keyName = userRoot + "\\" + subkey;
            var val = Registry.GetValue(keyName, valueName, "");
            if(val == null)
                return "";
            string tStr = Registry.GetValue(keyName, valueName, "").ToString();
            return tStr;
        }

        void WriteReg(string valueName, string POSvalue)
        {
            const string userRoot = "HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\D.P.Technology\\ESPRIT\\AddIns";
            const string subkey = "ESPRIT2025AddinProject.Connect\\" + regSettings + ToolbarInternalName + ".ToolBar";
            const string keyName = userRoot + "\\" + subkey;
            Registry.SetValue(keyName, valueName, POSvalue, RegistryValueKind.String);
        }
        #endregion Registry_Read_Write

        private static (string smallIconPath, string largeIconPath) EnsureToolbarIcons()
        {
            string assemblyLocation = Assembly.GetExecutingAssembly().Location;
            string baseDir = Path.GetDirectoryName(assemblyLocation) ?? AppDomain.CurrentDomain.BaseDirectory;
            string iconDir = Path.Combine(baseDir, "Icons");
            Directory.CreateDirectory(iconDir);

            string smallIcon = Path.Combine(iconDir, "tooth_16.bmp");
            string largeIcon = Path.Combine(iconDir, "tooth_32.bmp");

            if (!File.Exists(smallIcon))
            {
                GenerateToolbarIcon(smallIcon, 16);
            }

            if (!File.Exists(largeIcon))
            {
                GenerateToolbarIcon(largeIcon, 32);
            }

            return (smallIcon, largeIcon);
        }

        private static void GenerateToolbarIcon(string path, int size)
        {
            using (var bmp = new Bitmap(size, size))
            using (var g = Graphics.FromImage(bmp))
            {
                g.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.AntiAlias;
                var bgColor = Color.FromArgb(32, 70, 255);
                var accentColor = Color.White;
                g.Clear(bgColor);

                using (var brush = new SolidBrush(accentColor))
                {
                    var toothRect = new Rectangle((int)(size * 0.25), (int)(size * 0.15), (int)(size * 0.5), (int)(size * 0.55));
                    g.FillEllipse(brush, toothRect);

                    var rootRect = new Rectangle((int)(size * 0.35), (int)(size * 0.55), (int)(size * 0.3), (int)(size * 0.35));
                    g.FillPolygon(brush, new DrawingPoint[]
                    {
                        new DrawingPoint(rootRect.Left, rootRect.Top),
                        new DrawingPoint(rootRect.Right, rootRect.Top),
                        new DrawingPoint(rootRect.Right - (int)(size * 0.08), rootRect.Bottom),
                        new DrawingPoint(rootRect.Left + (int)(size * 0.08), rootRect.Bottom)
                    });
                }

                bmp.Save(path, ImageFormat.Bmp);
            }
        }

        private void ShowAddInLoadedIndicator()
        {
            string banner = $"[Abuts.fit Add-in] {DateTime.Now:yyyy-MM-dd HH:mm:ss}에 로드되었습니다.";
            LogToEspritOutputs(banner);
            ShowToast(banner);
        }

        // Heartbeat removed per request
        private void StartHeartbeat() { }
        private void StopHeartbeat() { }
        private void HeartbeatTimerOnTick(object sender, EventArgs e) { }

        private void LogToEspritOutputs(string message)
        {
            if (_espApp == null)
            {
                System.Diagnostics.Trace.WriteLine($"Connect: cannot log message (app null) - {message}");
                WriteDebugLog(message);
                return;
            }

            var logged = false;

            try
            {
                if (_espApp.OutputWindow != null)
                {
                    _espApp.OutputWindow.Visible = true;
                    _espApp.OutputWindow.Text(message + Environment.NewLine);
                    logged = true;
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Trace.WriteLine($"Connect: OutputWindow.Text failed - {ex.Message}");
                WriteDebugLog($"[OutputWindow fail] {message} / {ex.Message}");
            }

            if (!logged)
            {
                System.Diagnostics.Trace.WriteLine($"Connect: {message}");
                WriteDebugLog(message);
            }
        }

        private void WriteDebugLog(string message)
        {
            try
            {
                var dir = Path.GetDirectoryName(_debugLogPath);
                if (!string.IsNullOrEmpty(dir))
                {
                    Directory.CreateDirectory(dir);
                }
                File.AppendAllText(_debugLogPath, $"[{DateTime.Now:yyyy-MM-dd HH:mm:ss}] {message}{Environment.NewLine}");
            }
            catch
            {
                // ignore file log failure
            }
        }

        private void ShowToast(string message)
        {
            try
            {
                ThreadPool.QueueUserWorkItem(_ =>
                {
                    using (var toast = new AddInToastForm(message))
                    {
                        toast.Show();
                        System.Windows.Forms.Application.DoEvents();
                        Thread.Sleep(2500);
                        toast.Invoke(new Action(() => toast.Close()));
                    }
                });
            }
            catch
            {
                // ignore
            }
        }

        private sealed class AddInToastForm : Form
        {
            public AddInToastForm(string message)
            {
                FormBorderStyle = FormBorderStyle.None;
                StartPosition = FormStartPosition.Manual;
                ShowInTaskbar = false;
                TopMost = true;
                BackColor = Color.FromArgb(32, 70, 255);
                ForeColor = Color.White;
                Padding = new Padding(24, 18, 24, 18);

                var textLabel = new Label
                {
                    AutoSize = true,
                    Text = message,
                    Font = new Font("Segoe UI", 10, FontStyle.Bold),
                    ForeColor = Color.White,
                    BackColor = Color.Transparent
                };

                    Controls.Add(textLabel);
                    AutoSize = true;

                    var screen = Screen.PrimaryScreen?.WorkingArea ?? new Rectangle(0, 0, 800, 600);
                    Location = new DrawingPoint(
                        screen.Right - Width - 20,
                        screen.Bottom - Height - 20);
            }
        }
    }

}
