// change-log:
// - 2026-09-13: 상단 hero와 동일 gallery-1만 제외, 나머지 상세 이미지 복구.
// - 2026-09-13: acrodent.com 상세 이미지 OCR → 텍스트 블록 + 순수 제품 이미지.
// related files:
// - web/frontend/src/shared/store/storeCatalog.ts
// - web/frontend/src/pages/requestor/store/RequestorStoreProductPage.tsx

export type StoreContentBlock =
  | { type: "heading"; text: string }
  | { type: "text"; text: string }
  | { type: "list"; items: string[] }
  | { type: "image"; src: string; alt?: string };

export type StoreProductContent = {
  blurb?: string;
  description?: string;
  specs?: { label: string; value: string }[];
  blocks: StoreContentBlock[];
};

/** acrodent 상세(이미지)에서 OCR·분리한 스토어 상세 콘텐츠. */
export const STORE_PRODUCT_CONTENT: Record<string, StoreProductContent> = {
  "simple-abutment-2": {
    blurb: "For Submerged type · Anti-rotation form",
    description: "서브머지드 타입용 Simple Abutment [Non-Hex] Anti-rotation 형태입니다. 플랫 페이스로 회전을 억제하며, Pen·Pin·Healing·Gingival Shaper와 동일 색상 밴드(Follow color-band)로 규격을 맞춰 보철까지 이어갑니다.",
    specs: [
      { label: "품명", value: "치과용임플란트상부구조물" },
      { label: "모델명", value: "SS06-NC20외 265건" },
      { label: "의료기기 허가, 신고 번호", value: "제인13-1673호" },
      { label: "사용목적", value: "환자의 저작 기능 회복을 위해 사용하는 인공 치아와 같은 보철물을 지지하기 위하여 삽입" },
      { label: "사용방법", value: "상품상세설명 참조" },
      { label: "사용시 주의사항 및 보관방법", value: "상품상세설명 참조" },
      { label: "포장단위", value: "1set" },
      { label: "제조자/제조국", value: "(주)애크로덴트/대한민국" },
      { label: "보험청구코드", value: "L7552057" },
      { label: "나사", value: "M2.0×0.4P" },
      { label: "HEX", value: "1.20 (Acodent/Osstem/Neo/Megagen/Dio) · 1.28 (Dentium/Dentis)" },
      { label: "커프(C)", value: "S 2.0 / M 3.5 / L 5.0 mm" },
      { label: "직경 라인", value: "6·7·8·9·10 (Ø4.4~Ø7.9대)" },
    ],
    blocks: [
      { type: "heading", text: "Simple Abutment [Non-Hex] (Anti-rotation form)" },
      { type: "text", text: "보험청구코드 L7552057. 상단 포스트 높이(H) 5.0mm, 드라이버 HEX 1.20/1.28, 나사 M2.0×0.4P." },
      { type: "heading", text: "제품의 규격" },
      { type: "text", text: "치수: C(커프 높이), D(플레어 직경), H(포스트 높이), HD(HEX). 적용 임플란트군별로 Pd.No가 나뉩니다." },
      { type: "list", items: ["Acodent · Osstem · Neo-implant · Megagen · Dio — HEX 1.20 (예: S2761~S2785 계열)", "Dentium · Dentis — HEX 1.28 (예: S2771~S2790 계열)", "Cuff: Short 2.0mm / Middle 3.5mm / Long 5.0mm", "직경 라인 6·7·8·9·10 (D Ø4.4 / Ø4.9 / Ø5.9 / Ø6.9 / Ø7.9대)"] },
      { type: "image", src: "/store/content/simple-abutment-2/size-grid.jpg", alt: "치수 다이어그램: C/D/H/HD + 나사 M2.0×0.4P 도면" },
      { type: "image", src: "/store/content/simple-abutment-2/color-band.jpg", alt: "Simple Abutment 사이즈 그리드 3×5 (S/M/L × 6–10)" },
      { type: "heading", text: "제품의 특징 — Follow color-band" },
      { type: "text", text: "Provision → Pen → Pin → BoneShaper → Healing Abut. → GC/SA → GingivalShaper → Final 순으로 동일 색상 밴드를 따라 규격을 맞춥니다." },
      { type: "heading", text: "Pen·Pin으로 맞추는 15가지 규격" },
      { type: "text", text: "Pen·Pin 직경 5종 × 눈금높이 3칸(S/M/L) = 15가지. 같은 규격의 Healing·Simple Abut.을 적용하면 교합 조정 시간을 줄일 수 있습니다." },
      { type: "list", items: ["예: #7 부위를 10Pen으로 이니셜 드릴링 후 Initial 10Pin으로 육안 확인", "Size = 직경10 + 높이 S → 10S", "이후 Healing 10S, Simple Abut.(Final) 10S 적용"] },
    ],
  },
  "simple-abutment": {
    blurb: "For Submerged type",
    description: "서브머지드 타입용 Simple Abutment [Non-Hex]입니다. 커프 높이(S/M/L)와 직경 라인(6–10)으로 규격을 선택하며, Follow color-band로 시술·보철 기구와 색상을 맞춰 사용합니다.",
    specs: [
      { label: "품명", value: "치과용임플란트상부구조물" },
      { label: "모델명", value: "SS06-NC20 외 265건" },
      { label: "의료기기 허가, 신고 번호", value: "제인13-1673호" },
      { label: "사용목적", value: "환자의 저작 기능 회복을 위해 사용하는 인공 치아와 같은 보철물을 지지하기 위하여 삽입" },
      { label: "사용방법", value: "상품상세설명 참조" },
      { label: "사용시 주의사항 및 보관방법", value: "상품상세설명 참조" },
      { label: "포장단위", value: "1set" },
      { label: "제조자/제조국", value: "(주)애크로덴트/대한민국" },
      { label: "보험청구코드", value: "L7552057" },
      { label: "나사", value: "M2.0×P0.4" },
      { label: "HEX", value: "1.20 / 1.28 (임플란트 시스템별)" },
      { label: "커프(C)", value: "S 2.0 / M 3.5 / L 5.0 mm" },
    ],
    blocks: [
      { type: "heading", text: "Simple Abutment [Non-Hex]" },
      { type: "text", text: "보험청구코드 L7552057. 치수 C(커프)·D(직경)·H(포스트)·HD(HEX), 나사 M2.0×P0.4." },
      { type: "heading", text: "제품의 규격" },
      { type: "list", items: ["적용: Acodent / Osstem / Neo-implant / Megagen / Dio — HEX 1.20 (S2061~ 계열)", "적용: Dentium / Dentis — HEX 1.28 (S2071~ 계열)", "Cuff Short 2.0 / Middle 3.5 / Long 5.0 mm", "직경 라인 6·7·8·9·10"] },
      { type: "image", src: "/store/content/simple-abutment/size-grid.jpg", alt: "치수 다이어그램 C/D/H/HD + 나사" },
      { type: "image", src: "/store/content/simple-abutment/color-band.jpg", alt: "Simple Abutment 사이즈 그리드 S/M/L × 6–10" },
      { type: "heading", text: "Follow color-band" },
      { type: "text", text: "Pen·Pin·BoneShaper·Healing·GingivalShaper와 동일 색상으로 규격을 맞춰 Final 보철까지 연결합니다." },
    ],
  },
  "simple-healing-2": {
    blurb: "For Submerged type",
    description: "서브머지드 타입용 Healing Abutment입니다. 커프 높이(S/M/L)와 직경(6–10) 조합으로 연조직 성형을 돕고, Simple Abutment와 같은 Follow color-band로 규격을 맞춥니다. (simple-healing과 동일 SKU)",
    specs: [
      { label: "품명", value: "치과용임플란트상부구조물" },
      { label: "모델명", value: "SH06-H0C20 외 44건" },
      { label: "의료기기 허가, 신고 번호", value: "제인19-4012호" },
      { label: "사용목적", value: "환자의 저작 기능 회복을 위해 사용하는 인공 치아와 같은 보철물을 지지하기 위하여 삽입" },
      { label: "사용방법", value: "상품상세설명 참조" },
      { label: "사용시 주의사항 및 보관방법", value: "상품상세설명 참조" },
      { label: "포장단위", value: "1EA" },
      { label: "제조자/제조국", value: "(주)애크로덴트/대한민국" },
      { label: "HEX", value: "1.20 / 1.28 (임플란트 시스템별)" },
      { label: "헤드 높이(H)", value: "약 3.5 mm" },
      { label: "커프(C)", value: "S 2.0 / M 3.5 / L 5.0 mm" },
    ],
    blocks: [
      { type: "heading", text: "Healing Abutment" },
      { type: "text", text: "픽스처 식립 후 연조직 힐링을 위한 어버트먼트. 상단 표기(예: 8M)로 규격을 확인하고 HEX 드라이버로 체결합니다." },
      { type: "heading", text: "제품의 규격" },
      { type: "list", items: ["Acodent / Osstem / Neo / Megagen / Dio — HEX 1.20 (S1061~ 계열)", "Dentium / Dentis — HEX 1.28 (S1071~ 계열)", "Cuff S 2.0 / M 3.5 / L 5.0 mm", "직경 라인 6·7·8·9·10 (예: Ø5.4~Ø9.0대)"] },
      { type: "image", src: "/store/content/simple-healing-2/size-grid.jpg", alt: "치수 다이어그램 D/H/C/HD + 상단 8M 표기 예시" },
      { type: "image", src: "/store/content/simple-healing-2/color-band.jpg", alt: "Healing Abutment 사이즈 그리드 S/M/L × 6–10" },
      { type: "heading", text: "Follow color-band" },
      { type: "text", text: "Pen·Pin·BoneShaper와 동일 색상 밴드로 Healing → Simple Abut. → Final까지 규격을 유지합니다." },
    ],
  },
  "initial-kit": {
    blurb: "매일 똑같이 잘 심기 위한 키트 · 수평·수직 위치 확인 · BonePen Kit 업그레이드",
    description: "TheSimple Kit Initial(TSKLv2, Pd.No T7188)은 InitialPen·Cup·InitialPin·Trimmer·GBR Pen을 한 트레이에 구성한 이니셜 드릴링 키트입니다. 2-Step 드릴(Ø2.2×Ø2.8)로 위치를 잡고, Pin으로 상하악 수직·수평을 육안 확인합니다.",
    specs: [
      { label: "품목명", value: "치과임플란트시술용드릴" },
      { label: "모델명", value: "TSKL 외 / TSKLv2" },
      { label: "의료기기 허가, 신고 번호", value: "부산제신19-1062호 외" },
      { label: "사용목적", value: "사용자 매뉴얼 참조" },
      { label: "사용방법", value: "상품상세설명 참조" },
      { label: "사용시 주의사항 및 보관방법", value: "사용자 매뉴얼 참조" },
      { label: "포장단위", value: "Kit or EA" },
      { label: "제조자", value: "(주)애크로덴트" },
      { label: "제조국", value: "대한민국" },
      { label: "품질책임자/전화번호", value: "이상훈 / Tel : 055-314-4607" },
      { label: "Pd.No", value: "T7188" },
      { label: "키트 모델", value: "TSKLv2" },
    ],
    blocks: [
      { type: "heading", text: "매일 똑같이 잘 심기 위한 키트 \"Initial Kit\"" },
      { type: "text", text: "TheSimple Kit Initial — Pd.No T7188 · 모델 TSKLv2 · 의료기기 신고번호 부산제신19-1062호." },
      { type: "heading", text: "구성품" },
      { type: "list", items: ["InitialPen 2종 (Short / Middle) — 모델 4F2228S·4F2228M, Pd.No T7094·T7095", "Cup 5종 (Ø6·7·8·9·10, 색상 구분) — BPC06028~BPC10028", "InitialPin 5종 (IP06~IP10, Cup과 동일 직경·색상) — Pd.No T7101~T7105", "Bone Trimmer Ø4.0 (B140, Pd.No T7093)", "GBR Pen (BPGBR, Pd.No T7013)"] },
      { type: "image", src: "/store/content/initial-kit/tray.jpg", alt: "Initial Kit 트레이·구성품 다이어그램" },
      { type: "heading", text: "BonePen과의 차이" },
      { type: "list", items: ["2-Step 드릴(Ø2.2×Ø2.8)로 BonePen보다 위치 잡기가 용이", "다수치 식립 시 Pen은 핸드피스에 체결한 채 Cup만 다른 사이즈로 교체", "골 평탄화용 Ø4.0 Trimmer 포함"] },
      { type: "heading", text: "시술 흐름" },
      { type: "list", items: ["1. Initial — STEP1 InitialPen 드릴링 → STEP2 InitialPin 수직 확인", "2. Install — STEP3 Final drilling (필요 시 countersink)", "3. Check — STEP4 Fixture 식립 → STEP5 BoneShaping(순차) → STEP6 CheckPin으로 최종 위치·인접 임플란트 평행 확인", "4. Prosthetics — Healing Abutment → Simple Abutment", "인접치(#46·#47)에 STEP1~6 반복"] },
      { type: "heading", text: "직경 선택" },
      { type: "list", items: ["부적합(예: 8mm) — 인접치에 걸려 들어가지 않음", "적합(예: 7mm) — 드릴팁이 치조골에 접촉"] },
      { type: "heading", text: "InitialPen 사용 · 속도와 주수" },
      { type: "list", items: ["핸드피스 20:1 기어비, 300~1,500 RPM, 45~55 Torque, 주수하 사용", "Cup 측면을 인접치 측면에 살짝 밀착", "양손 파지 — 삭제 지점 이탈·Cup/드릴 분리 방지", "구강 내 이동 시 드릴 회전이 완전히 멈춘 뒤 이동"] },
      { type: "heading", text: "Pen 조립 · 분리" },
      { type: "list", items: ["조립: Pen 선택 → Cup 선택 → 딸깍 소리가 날 때까지 끼움 → 사용", "분리: 세 손가락으로 Cup을 잡고, 핸드피스(제품이 꽂힌 상태)를 다른 손으로 잡아 Cup을 당김"] },
      { type: "heading", text: "세척 · 멸균" },
      { type: "list", items: ["Cup과 드릴은 분리 세척 (멸균 시에는 조립)", "사용 후 내부 치조골을 제거하고 세척·멸균 후 보관", "Autoclave는 Cup·드릴을 조립한 상태로 실시"] },
      { type: "heading", text: "Trimmer · GBR Pen" },
      { type: "list", items: ["Trimmer Ø4.0 — 20:1 / 1,000 RPM / 45~55 Torque / 주수하 (골 평탄화)", "GBR Pen — 피질골 천공·자가골 채취. 20:1 / 300 RPM / 45~55 Torque / 주수하, 최대 약 0.4cc(8~10회 드릴링)"] },
      { type: "heading", text: "InitialPin" },
      { type: "text", text: "상하악 수직 높이 확인·가상 치아 역할로 수평 위치를 잡습니다. 티타늄 재사용. 3칸 눈금(각 1.5mm)으로 수직 공간을 육안 확인하며, 길이 측정 기능은 없고 분리 사용하지 않습니다. Long / Middle / Short." },
      { type: "heading", text: "Follow color-band · 15가지 규격" },
      { type: "text", text: "Pen·Pin 직경 5종 × 눈금 높이 3칸 = 15가지. 예: #7을 10Pen으로 이니셜 드릴링 후 Initial 10Pin(S) 확인 → Healing 10S · Simple Abut.(Final) 10S 적용으로 교합 조정을 줄입니다." },
    ],
  },
  "check-kit": {
    blurb: "임플란트 식립 후 눈에 보이지 않는 Connection 문제 해결 · 타사 호환",
    description: "TheSimple Kit Check(TSKC, Pd.No T7150)는 Fixture 식립 후 CheckPin으로 패스·교합 높이를 확인하고, BoneShaper S·M/L로 cortical bone를 성형해 연결부 간섭을 줄이는 키트입니다. Submerged Type Fixture(양측 22° 테이퍼)에 사용합니다.",
    specs: [
      { label: "품목명", value: "치과임플란트시술용드릴 외" },
      { label: "모델명", value: "TSKC 외" },
      { label: "의료기기 허가, 신고 번호", value: "제신19-1062호 외" },
      { label: "사용목적", value: "사용자 매뉴얼 참조" },
      { label: "사용방법", value: "상품상세설명 참조" },
      { label: "사용시 주의사항 및 보관방법", value: "사용자 매뉴얼 참조" },
      { label: "포장단위", value: "KIT or EA" },
      { label: "제조자/제조국", value: "(주)애크로덴트/대한민국" },
      { label: "품질관리자/전화번호", value: "이상훈 / Tel : 055-314-4607" },
      { label: "Pd.No", value: "T7150" },
      { label: "키트 모델", value: "TSKC" },
    ],
    blocks: [
      { type: "heading", text: "잘 심은 임플란트에 깔끔한 보철을" },
      { type: "text", text: "식립 후 보이지 않는 Connection 문제를 해결합니다. ※ Submerged Type Fixture(양측 22° 테이퍼)에 사용 가능." },
      { type: "heading", text: "구성품" },
      { type: "list", items: ["CheckPin 5종 (CP06–CP10, Ø6.0–Ø10.0)", "BoneShaper S 5종 (BS06V3–BS10V3)", "BoneShaper M/L 5종 (BS06ML–BS10ML)"] },
      { type: "image", src: "/store/content/check-kit/tray.jpg", alt: "Check Kit 스펙·구성품 다이어그램" },
      { type: "heading", text: "CheckPin" },
      { type: "text", text: "픽스처 식립 후 내부에 삽입해 (1) 식립 패스 확인 (2) 픽스처–교합면 높이 재확인. 3칸 눈금(각 1.5mm)으로 상하악 수직 공간을 육안 확인합니다." },
      { type: "heading", text: "BoneShaper" },
      { type: "list", items: ["Cortical bone와 어버트먼트 간섭 제거를 위해 픽스처에 수직으로 세워 삭제", "안전한 보철을 위해 식립 후 항상 사용 권장", "작은 사이즈부터 순차 사용 (예: 9번 사용 시 6→7→8→9)", "20:1 / 1,000~1,500 rpm / 45~55 Torque / 주수하 / 3~5초, 부족 시 2~3회 반복"] },
      { type: "image", src: "/store/content/check-kit/boneshaper.jpg", alt: "BoneShaper Before/After 골성형 비교 다이어그램 (임상 갤러리 제외)" },
      { type: "heading", text: "주의사항" },
      { type: "list", items: ["인접치에 주의하여 수직으로 사용", "비멸균 의료기기 — 시술 전 Autoclave 습열멸균(132°C, 15분)"] },
    ],
  },
  "prosthetic-kit": {
    blurb: "심플하게 시작했다면 심플하게 마무리 — 스트레스 없는 보철",
    description: "TheSimple Kit Prosthetics(TSKP, Pd.No T7151)는 GingivalShaper와 Handpiece/Wrench HEX-driver, Torque wrench를 구성한 보철 마무리 키트입니다. Simple Abutment 마진 치은을 정리하고 Hex 1.20 나사를 체결·토크합니다.",
    specs: [
      { label: "품명", value: "치과용임플란트시술기구 외" },
      { label: "모델명", value: "TSKP 외" },
      { label: "의료기기 허가, 신고 번호", value: "제신19-1054호 외" },
      { label: "사용목적", value: "상품상세설명 참조" },
      { label: "사용방법", value: "상품상세설명 참조" },
      { label: "사용시 주의사항 및 보관방법", value: "상품상세설명 참조" },
      { label: "포장단위", value: "Kit 또는 1EA" },
      { label: "제조자/제조국", value: "(주)애크로덴트/대한민국" },
      { label: "품질책임자/전화번호", value: "이상훈 / Tel : 055-314-4607" },
      { label: "Pd.No", value: "T7151" },
      { label: "키트 모델", value: "TSKP" },
    ],
    blocks: [
      { type: "heading", text: "TheSimple Kit Prosthetics" },
      { type: "text", text: "의료기기 신고번호 제신19-1054호. Follow color-band로 Initial·Check 단계와 규격을 이어 보철을 마무리합니다." },
      { type: "heading", text: "구성품" },
      { type: "list", items: ["GingivalShaper (Short/Middle 계열, GS06V1–GS010V1)", "Handpiece HEX-driver (HD12, Hex 1.20)", "Wrench HEX-driver Short/Middle (WD12S / WD12M)", "Torque wrench (Hand Type)"] },
      { type: "image", src: "/store/content/prosthetic-kit/tray.jpg", alt: "Prosthetic Kit 트레이·구성품 다이어그램" },
      { type: "heading", text: "GingivalShaper" },
      { type: "text", text: "Simple Abutment 숄더를 덮는 치은을 삭제해 깔끔한 마진을 확보합니다. 타사 어버트먼트에는 호환되지 않으며, 동일 규격끼리 사용합니다 (예: GS 8 → Simple Abut. 8S 또는 8M)." },
      { type: "list", items: ["엔도용(추천) 또는 임플란트용 핸드피스에 체결", "주수하, 최대회전수 내에서 3~5초 (1:1 기준), 부족 시 1~2회 반복", "인접치 주의, 수직 사용"] },
      { type: "heading", text: "HEX-driver · Torque wrench" },
      { type: "list", items: ["Handpiece HEX: 핸드피스 체결, speed 50rpm 미만", "Wrench HEX: 렌치에 체결 후 상부구조물/고정체 결합", "Torque wrench: W-Adaptor 체결(A) → 방향 설정(B) → 눈금에 맞게 당김(C)"] },
    ],
  },
  "initial-pen": {
    blurb: "2-Step(Ø2.2×Ø2.8) 드릴 · Cup과 체결해 이니셜 골삭제",
    description: "Initial Pen은 Cup과 체결해 사용하는 2-Step(Ø2.2×Ø2.8) 이니셜 드릴입니다. Short/Middle 길이로 제공되며, 인접치에 Cup을 밀착해 삭제 위치를 안정적으로 잡습니다.",
    specs: [
      { label: "품목명", value: "치과임플란트시술용드릴" },
      { label: "모델명", value: "BT40외 49건" },
      { label: "의료기기 허가, 신고 번호", value: "제신 19-1047 호" },
      { label: "사용목적", value: "임플란트 시술에서 임플란트용 핸드피스에 부착하여 골을 삭제하는 기구" },
      { label: "사용방법", value: "상품상세설명 참조" },
      { label: "사용시 주의사항 및 보관방법", value: "상품상세설명 참조" },
      { label: "포장단위", value: "EA" },
      { label: "제조자/제조국", value: "(주)애크로덴트/대한민국" },
      { label: "품질책임자/전화번호", value: "이상훈 / Tel : 055-314-4607" },
      { label: "길이", value: "Short 약 30.5mm / Middle 약 33.0mm" },
      { label: "팁", value: "Ø2.2 → Ø2.8, 최대 삭제길이 약 7.5mm" },
      { label: "권장 RPM", value: "300~1,500 (20:1), Torque 45~55" },
    ],
    blocks: [
      { type: "heading", text: "Initial Pen (Short / Middle)" },
      { type: "text", text: "임플란트용 핸드피스에 부착해 치조골을 삭제하는 기구. TheSimple Kit Initial 구성품으로도 제공됩니다." },
      { type: "image", src: "/store/content/initial-pen/pens.jpg", alt: "Initial Pen Short / Middle" },
      { type: "heading", text: "적합한 직경 선택" },
      { type: "text", text: "부적합 직경(예: 인접치에 걸리는 8mm)은 드릴팁이 치조골에 닿지 않을 수 있습니다. 치간·최종 보철 직경에 맞는 Cup/Pen을 선택하세요." },
      { type: "image", src: "/store/content/initial-pen/fit-compare.jpg", alt: "적합/부적합 직경 비교 일러스트 (X vs O)" },
      { type: "heading", text: "사용방법" },
      { type: "list", items: ["핸드피스 20:1, 300~1,500 RPM, 45~55 Torque, 주수하", "Cup 측면을 인접치에 살짝 밀착, 양손 파지", "이동 시 회전이 완전히 멈춘 후 이동", "권장 사용 횟수 30회 이내"] },
      { type: "heading", text: "펜 조립 · 분리" },
      { type: "list", items: ["조립: Pen 선택 → Cup 선택 → 딸깍까지 끼움 → 사용", "분리: 세 손가락으로 Cup을 잡고 핸드피스를 고정한 채 당김", "세척은 분리, Autoclave 멸균은 조립 상태"] },
    ],
  },
  "pen": {
    blurb: "발치 즉시 식립 · 드릴링 패스 수정 · 플랩리스 이니셜 드릴링",
    description: "Lindemann Pen(LD28L)은 끝이 뾰족하고 측방 블레이드가 있어 경사골에서도 미끄러짐 없이 초기 위치를 잡고, 발치 즉시 식립 시 측방 패스 수정에 유리합니다. Initial·BonePen Kit Light Cup과 결합할 수 있습니다(Cup 별매).",
    specs: [
      { label: "품목명", value: "치과임플란트시술용드릴" },
      { label: "모델명", value: "LD28L" },
      { label: "의료기기 허가, 신고 번호", value: "제신19-1047호" },
      { label: "사용목적", value: "사용자 매뉴얼 참조" },
      { label: "사용방법", value: "상품상세설명 참조" },
      { label: "사용시 주의사항 및 보관방법", value: "사용자 매뉴얼 참조" },
      { label: "포장단위", value: "EA" },
      { label: "제조자/제조국", value: "(주)애크로덴트 / 대한민국" },
      { label: "품질책임자/전화번호", value: "이상훈 / Tel : 055-314-4607" },
      { label: "길이", value: "Long 약 37.0mm" },
      { label: "직경", value: "Ø2.8" },
      { label: "최대 삭제깊이", value: "Cup 미체결 약 18.3mm / Cup 체결 약 13.2mm 이내" },
      { label: "권장 RPM", value: "300~1,500, Torque 45~55 N·cm" },
    ],
    blocks: [
      { type: "heading", text: "Lindemann Pen" },
      { type: "heading", text: "제품 특징" },
      { type: "list", items: ["끝이 뾰족해 초기 위치 결정이 쉽고, 날카로운 측방향 삭제 가능", "경사진 골에서도 미끄러짐 없이 삭제, 발치즉시 식립 시 측방 패스 수정에 활용", "Cup과 결합 가능 — 인접치 간격·교합 높이 가늠에 편리 (Cup 별매)", "스프링 구조로 Cup을 인접치와 비슷한 높이에 유지해 간격 잡기가 용이"] },
      { type: "image", src: "/store/content/pen/full.jpg", alt: "Lindemann Pen 전체 + Cup 체결" },
      { type: "image", src: "/store/content/pen/tip.jpg", alt: "팁 클로즈업(나선·블레이드)" },
      { type: "heading", text: "사용방법 요지" },
      { type: "list", items: ["Autoclave 습열멸균(132°C, 15분) 후 사용", "주수하 수직 사용, 양손 파지, 권장 30회 이내", "마찰열 감소를 위해 식염수 주수 필수"] },
    ],
  },
  "cup": {
    blurb: "Initial·Light Pen에 체결 · 크라운과 유사한 직경 선택",
    description: "Cup은 Initial Pen·BonePen Kit Light Pen에 꽂아 쓰는 가이드 기구입니다. 최종 크라운(보철)과 비슷한 직경(Ø6–10)을 색상으로 구분해 선택하며, 단독 사용하지 않고 반드시 Pen에 체결합니다.",
    specs: [
      { label: "품목명", value: "치과용임플란트시술기구" },
      { label: "모델명", value: "BPC06D24외 9건" },
      { label: "의료기기 허가, 신고 번호", value: "제신 17-512 호" },
      { label: "사용목적", value: "치과용 임플란트를 시술하는 데에 사용되는 기구이다." },
      { label: "사용방법", value: "상품상세설명 참조" },
      { label: "사용시 주의사항 및 보관방법", value: "상품상세설명 참조" },
      { label: "포장단위", value: "EA" },
      { label: "제조자/제조국", value: "(주)애크로덴트/대한민국" },
      { label: "품질책임자/전화번호", value: "이상훈 / Tel : 055-314-4607" },
      { label: "규격", value: "Ø6.0 / Ø7.0 / Ø8.0 / Ø9.0 / Ø10.0" },
      { label: "모델 예", value: "BPC06028–BPC10028 (Pd.No T7078–T7082)" },
    ],
    blocks: [
      { type: "heading", text: "Cup [Light & Initial]" },
      { type: "heading", text: "규격 · 색상" },
      { type: "list", items: ["6 · Ø6.0 (예: BPC06028 / T7078)", "7 · Ø7.0 (BPC07028 / T7079)", "8 · Ø8.0 (BPC08028 / T7080)", "9 · Ø9.0 (BPC09028 / T7081)", "10 · Ø10.0 (BPC10028 / T7082)"] },
      { type: "image", src: "/store/content/cup/row.jpg", alt: "Cup Ø6–10 색상·모델 스펙표" },
      { type: "heading", text: "사용방법" },
      { type: "list", items: ["치간 거리·최종 보철 크기에 맞는 직경 선택 (인접치 간섭·여유 간격 육안 확인)", "드릴(Pen)에 결합 후 핸드피스 체결 — 20:1, 300~1,500 RPM, 45~55 Torque", "Cup 측면을 인접치에 살짝 밀착, 주수하·양손 사용", "Cup·드릴 분리 세척, 습열멸균 조건 준수"] },
    ],
  },
  "initial-pin": {
    blurb: "Pen 삭제 후 가상 크라운 역할 · 수평·수직 공간 확인",
    description: "InitialPin은 Initial Pen으로 삭제한 치조골에 Cup과 같은 직경(색상)의 핀을 꽂아 가상의 치아 역할을 합니다. 상하악 수직 높이와 수평 위치를 육안 확인하고, 티타늄 소재로 재사용이 가능합니다.",
    specs: [
      { label: "품목명", value: "치과용임플란트시술기구" },
      { label: "모델명", value: "EX14외 11건" },
      { label: "의료기기 허가, 신고 번호", value: "제신 19-1088 호" },
      { label: "사용목적", value: "치과용 임플란트를 시술하는 데에 사용되는 기구이다." },
      { label: "사용방법", value: "사용자 매뉴얼 참조" },
      { label: "사용시 주의사항 및 보관방법", value: "사용자 매뉴얼 참조" },
      { label: "포장단위", value: "EA" },
      { label: "제조자/제조국", value: "(주)애크로덴트/대한민국" },
      { label: "품질관리자/전화번호", value: "이상훈 / Tel : 055-314-4607" },
      { label: "모델", value: "IP06–IP10" },
      { label: "직경", value: "Ø6.0–Ø10.0" },
      { label: "Pd.No", value: "T7101–T7105" },
      { label: "눈금", value: "3칸 × 1.5mm, 본체 약 7mm" },
    ],
    blocks: [
      { type: "heading", text: "InitialPin" },
      { type: "text", text: "임플란트 시술 시 상악·하악 간 수직 높이를 확인하고, 가상 치아로 수평 위치를 잡아 줍니다. ※ 티타늄으로 장기 재사용 가능." },
      { type: "image", src: "/store/content/initial-pin/hero.jpg", alt: "InitialPin 제품·치수 콜아웃" },
      { type: "heading", text: "규격" },
      { type: "list", items: ["IP06 Ø6.0 / IP07 Ø7.0 / IP08 Ø8.0 / IP09 Ø9.0 / IP10 Ø10.0", "높이 눈금 Long / Middle / Short (3칸)", "삽입부 Ø2.8 → 팁 Ø2.2"] },
      { type: "image", src: "/store/content/initial-pin/heights.jpg", alt: "Long / Middle / Short 높이 눈금" },
      { type: "heading", text: "사용방법" },
      { type: "list", items: ["삭제된 치조골에 삽입 후 상하악 수직 공간 육안 확인", "3칸 눈금이 상하로 움직여 수직 공간을 확인 (정밀 길이측정 기능 아님, 분리 사용 금지)", "안전홀(C)에 의료용 실(≥30cm) 매듭 → 체결부(A) 삽입 → 교합 밀착 후 눈금 확인 → 제거", "멸균: Autoclave 132°C, 15분"] },
      { type: "heading", text: "15가지 규격 매칭" },
      { type: "text", text: "Pen·Pin 직경 5종 × 눈금 3칸 = 15가지. 예: 10Pen → Initial 10Pin 확인 → Healing/Simple Abut. 10S 적용으로 교합 조정 시간 단축." },
    ],
  },
  "check-pin": {
    blurb: "Fixture 식립 후 패스·교합 높이 확인",
    description: "CheckPin은 Submerged Fixture 식립 후 픽스처 내부에 삽입해 식립 패스와 교합면까지의 수직 공간을 확인하는 기구입니다. 1차 수술에서 수직 공간을 확보하면 2차 수술·교합 조정이 수월해집니다.",
    specs: [
      { label: "품목명", value: "치과용임플란트시술기구" },
      { label: "모델명", value: "EX14외 11건" },
      { label: "의료기기 허가, 신고 번호", value: "제신 19-1088 호" },
      { label: "사용목적", value: "치과용 임플란트를 시술하는 데에 사용되는 기구이다." },
      { label: "사용방법", value: "사용자 매뉴얼 참조" },
      { label: "사용시 주의사항 및 보관방법", value: "사용자 매뉴얼 참조" },
      { label: "포장단위", value: "EA" },
      { label: "제조자/제조국", value: "(주)애크로덴트/대한민국" },
      { label: "품질관리자/전화번호", value: "이상훈 / Tel : 055-314-4607" },
      { label: "모델", value: "CP06–CP10" },
      { label: "직경", value: "Ø6.0–Ø10.0" },
      { label: "Pd.No", value: "T7134–T7138" },
      { label: "눈금", value: "3칸 × 1.5mm, 본체 약 7mm" },
    ],
    blocks: [
      { type: "heading", text: "CheckPin" },
      { type: "text", text: "픽스처 식립 후 내부에 삽입하여 (1) 식립 패스 확인 (2) 픽스처와 교합면 높이 재확인." },
      { type: "heading", text: "규격" },
      { type: "list", items: ["CP06 Ø6.0 · CP07 Ø7.0 · CP08 Ø8.0 · CP09 Ø9.0 · CP10 Ø10.0", "의료기기 신고번호 제신19-1088호"] },
      { type: "image", src: "/store/content/check-pin/row.jpg", alt: "CheckPin Ø6–10 색상 라인" },
      { type: "heading", text: "사용방법" },
      { type: "list", items: ["상하악 수직 공간 육안 확인용 — 3칸 눈금 상하 이동", "안전홀에 의료용 실 매듭 → Fixture 홈에 체결부 삽입 → 교합 밀착 후 눈금 확인 → 제거", "정밀 길이측정 기능 없음, 사용자 분리 사용 금지", "Autoclave 132°C, 15분 후 사용"] },
    ],
  },
  "bone-shaper": {
    blurb: "Fixture 식립 후 Healing 체결을 위한 cortical bone 삭제성형",
    description: "BoneShaper S(및 M/L)는 픽스처 식립 후 핸드피스에 연결해 cortical bone를 성형하는 드릴입니다. Healing·어버트먼트와 골 간섭을 줄이고, 작은 사이즈부터 순차 사용하는 것을 권장합니다.",
    specs: [
      { label: "품목명", value: "치과임플란트시술용드릴" },
      { label: "모델명", value: "BS6V2외 9건" },
      { label: "의료기기 허가, 신고 번호", value: "부산 제신 12-8 호" },
      { label: "사용목적", value: "임플란트 시술에서 임플란트용 핸드피스에 부착하여 골을 삭제하는 기구이다." },
      { label: "사용방법", value: "상품상세설명 참조" },
      { label: "사용시 주의사항 및 보관방법", value: "사용자 매뉴얼 참조" },
      { label: "포장단위", value: "EA" },
      { label: "제조자/제조국", value: "(주)애크로덴트/대한민국" },
      { label: "품질책임자/전화번호", value: "이상훈 / Tel : 055-314-4607" },
      { label: "BoneShaper S 모델", value: "BS06V3–BS10V3 (Size 6S–10S)" },
      { label: "BoneShaper M/L 모델", value: "BS06ML–BS10ML (Size 6ML–10ML)" },
      { label: "권장 조건", value: "20:1 / 1,000~1,500 rpm / 45~55 Torque / 주수하" },
    ],
    blocks: [
      { type: "heading", text: "BoneShaper S" },
      { type: "text", text: "임플란트용 핸드피스에 부착해 골을 삭제하는 기구. TheSimple Kit Check 구성품." },
      { type: "heading", text: "규격 (S)" },
      { type: "list", items: ["6S BS06V3 Ø5.8 · 7S BS07V3 Ø6.8 · 8S BS08V3 Ø7.8 · 9S BS09V3 Ø8.8 · 10S BS10V3 Ø9.8 (L 28.0mm)", "Pd.No T7041–T7045 · 신고번호 부산 제신12-8호"] },
      { type: "image", src: "/store/content/bone-shaper/s-row.jpg", alt: "BoneShaper S 색상 라인 6–10" },
      { type: "heading", text: "BoneShaper M/L (요약)" },
      { type: "text", text: "M/L 라인(BS06ML–BS10ML)도 동일하게 픽스처에 수직으로 세워 cortical bone–어버트먼트 간섭을 제거합니다. 식립 후 항상 사용 권장." },
      { type: "list", items: ["6ML–10ML / Pd.No T7139–T7143", "신고번호: 제신19-1047호"] },
      { type: "image", src: "/store/content/bone-shaper/ml-row.jpg", alt: "BoneShaper M/L 색상 라인 6–10" },
      { type: "image", src: "/store/content/bone-shaper/gallery-ml-1.jpg", alt: "BoneShaper M/L 제품" },
      { type: "image", src: "/store/content/bone-shaper/tray.jpg", alt: "BoneShaper 트레이·구성" },
      { type: "heading", text: "사용방법" },
      { type: "list", items: ["적합한 사이즈 선택 후 핸드피스 체결", "작은 사이즈부터 순차 사용 (9번이면 6부터)", "Submerged Fixture 내부 구멍에 커넥션부 최대한 삽입", "수직으로 살짝 가압, 주수하 3~5초, 부족 시 2~3회 반복", "사용 후 초음파 세척·상온 건조"] },
      { type: "heading", text: "주의사항" },
      { type: "list", items: ["인접치에 주의하여 수직 사용", "비멸균 — Autoclave 132°C, 15분"] },
    ],
  },
  "gingival-shaper": {
    blurb: "Simple Abutment margin 부위 치은 삭제용",
    description: "GingivalShaper는 Simple Abutment 숄더를 덮는 치은을 삭제해 인상 채득용 마진을 확보하는 절삭 기구입니다. Simple Abutment Prosthetic part와만 호환되며 동일 규격을 사용해야 합니다.",
    specs: [
      { label: "품명", value: "의료용절삭기구" },
      { label: "모델명", value: "GS06V1외 41건" },
      { label: "의료기기 허가, 신고 번호", value: "부산 제신 11-98 호" },
      { label: "사용목적", value: "천자기, 천공기 및 핸드피스 등에 사용하는 절삭용 버(burr), 절삭용 디스크, 광택용 휠, 스트립 등의 기구. 레이저, 수술기용 디스크를 포함한다." },
      { label: "사용방법", value: "상품상세설명 참조" },
      { label: "사용시 주의사항 및 보관방법", value: "상품상세설명 참조" },
      { label: "포장단위", value: "EA" },
      { label: "제조자/제조국", value: "(주)애크로덴트/대한민국" },
      { label: "품질책임자/전화번호", value: "이상훈 / Tel : 055-314-4607" },
      { label: "모델", value: "GS06V1–GS010V1" },
      { label: "직경 예", value: "Ø5.6–Ø9.6대" },
    ],
    blocks: [
      { type: "heading", text: "GingivalShaper" },
      { type: "text", text: "깔끔한 마진 확보로 간편한 인상 채득이 가능합니다. ※ 타사 어버트먼트에는 호환되지 않습니다." },
      { type: "heading", text: "규격 매칭" },
      { type: "text", text: "예: GingivalShaper 8 사용 시 Simple Abutment 8S 또는 8M 사용." },
      { type: "list", items: ["GS06V1–GS010V1 (Pd.No T7026–T7030)", "신고번호: 부산 제신11-98호"] },
      { type: "image", src: "/store/content/gingival-shaper/row.jpg", alt: "GingivalShaper 규격 라인" },
      { type: "heading", text: "사용방법" },
      { type: "list", items: ["상부구조물 규격에 맞는 제품 선택 → 핸드피스 체결 (엔도용 추천 또는 임플란트용)", "상부구조물에 밀착 후 주수하, 최대회전수 내 3~5초 (1:1 기준), 부족 시 1~2회", "이동 전 완전 정지, 내면 치은 잔사 제거 후 초음파 세척", "인접치 주의, 수직 사용"] },
    ],
  },
  "hex-driver": {
    blurb: "Hex 1.20 나사를 조이는 Wrench HEX-driver",
    description: "Wrench HEX-driver는 임플란트 구성품 결합 시 Hex 1.20 나사를 조이는 기구입니다. Short·Middle 길이로 제공되며 TheSimple Kit Prosthetics에 포함됩니다.",
    specs: [
      { label: "품명", value: "치과임플란트시술용스크루드라이버" },
      { label: "모델명", value: "HA25S외 7건" },
      { label: "의료기기 허가, 신고 번호", value: "제신 19-1048 호" },
      { label: "사용목적", value: "임플란트 시술시 구성품들을 결합하는 과정에서 나사를 조이는 기구이다." },
      { label: "사용방법", value: "상품상세설명 참조" },
      { label: "사용시 주의사항 및 보관방법", value: "상품상세설명 참조" },
      { label: "포장단위", value: "EA" },
      { label: "제조자/제조국", value: "(주)애크로덴트/대한민국" },
      { label: "품질책임자/전화번호", value: "이상훈 / Tel : 055-314-4607" },
      { label: "모델", value: "WD12S (Short) / WD12M (Middle)" },
      { label: "길이", value: "Short 약 20.0mm / Middle 약 24.0mm" },
      { label: "HEX", value: "1.20" },
      { label: "Pd.No", value: "T7145 / T7146" },
    ],
    blocks: [
      { type: "heading", text: "Wrench HEX-driver (Short / Middle)" },
      { type: "text", text: "임플란트 시술 시 구성품을 결합하는 과정에서 나사를 조이는 기구. 신고번호 제신19-1048호." },
      { type: "image", src: "/store/content/hex-driver/drivers.jpg", alt: "HEX-driver Short / Middle" },
      { type: "heading", text: "사용방법" },
      { type: "list", items: ["제품을 선택해 렌치에 체결", "상부구조물(또는 고정체)에 체결해 대상물로 이동 후 결합", "시술 전 Autoclave 습열멸균(132°C, 15분)"] },
    ],
  },
  "torque-wrench": {
    blurb: "나사를 설정 토크로 조이는 Hand Type 토크 렌치",
    description: "Torque wrench(Hand Type)는 임플란트 구성품 결합 시 나사를 지정 토크로 조이는 기구입니다. W-Adaptor를 체결하고 방향·눈금을 설정해 사용합니다.",
    specs: [
      { label: "품명", value: "치과용임플란트시술기구" },
      { label: "모델명", value: "EX14외 11건" },
      { label: "의료기기 허가, 신고 번호", value: "제신 19-1088 호" },
      { label: "사용목적", value: "치과용 임플란트를 시술하는 데에 사용되는 기구이다." },
      { label: "사용방법", value: "상품상세설명 참조" },
      { label: "사용시 주의사항 및 보관방법", value: "상품상세설명 참조" },
      { label: "포장단위", value: "EA" },
      { label: "제조자/제조국", value: "(주)애크로덴트/대한민국" },
      { label: "품질책임자/전화번호", value: "이상훈 / Tel : 055-314-4607" },
      { label: "모델", value: "TWH (Hand Type)" },
      { label: "Pd.No", value: "T7121" },
    ],
    blocks: [
      { type: "heading", text: "Torque wrench" },
      { type: "text", text: "치과용 임플란트 시술 기구. 신고번호 제신19-1088호." },
      { type: "image", src: "/store/content/torque-wrench/body.jpg", alt: "Torque wrench 본체" },
      { type: "image", src: "/store/content/torque-wrench/parts.jpg", alt: "토크 방향·눈금(A/B/C) 사용 다이어그램" },
      { type: "heading", text: "사용방법" },
      { type: "list", items: ["W-Adaptor를 체결부(A)에 체결", "B 부분을 당겨 회전시켜 토크 방향 설정", "C 부분을 천천히 당겨 토크 눈금에 맞게 사용", "시술 전 Autoclave 132°C, 15분"] },
    ],
  },
  "simple-healing": {
    blurb: "For Submerged type",
    description: "서브머지드 타입용 Healing Abutment입니다. 커프 높이(S/M/L)와 직경(6–10) 조합으로 연조직 성형을 돕고, Simple Abutment와 같은 Follow color-band로 규격을 맞춥니다. (simple-healing과 동일 SKU)",
    specs: [
      { label: "품명", value: "치과용임플란트상부구조물" },
      { label: "모델명", value: "SH06-H0C20 외 44건" },
      { label: "의료기기 허가, 신고 번호", value: "제인19-4012호" },
      { label: "사용목적", value: "환자의 저작 기능 회복을 위해 사용하는 인공 치아와 같은 보철물을 지지하기 위하여 삽입" },
      { label: "사용방법", value: "상품상세설명 참조" },
      { label: "사용시 주의사항 및 보관방법", value: "상품상세설명 참조" },
      { label: "포장단위", value: "1EA" },
      { label: "제조자/제조국", value: "(주)애크로덴트/대한민국" },
      { label: "HEX", value: "1.20 / 1.28 (임플란트 시스템별)" },
      { label: "헤드 높이(H)", value: "약 3.5 mm" },
      { label: "커프(C)", value: "S 2.0 / M 3.5 / L 5.0 mm" },
    ],
    blocks: [
      { type: "heading", text: "Healing Abutment" },
      { type: "text", text: "픽스처 식립 후 연조직 힐링을 위한 어버트먼트. 상단 표기(예: 8M)로 규격을 확인하고 HEX 드라이버로 체결합니다." },
      { type: "heading", text: "제품의 규격" },
      { type: "list", items: ["Acodent / Osstem / Neo / Megagen / Dio — HEX 1.20 (S1061~ 계열)", "Dentium / Dentis — HEX 1.28 (S1071~ 계열)", "Cuff S 2.0 / M 3.5 / L 5.0 mm", "직경 라인 6·7·8·9·10 (예: Ø5.4~Ø9.0대)"] },
      { type: "image", src: "/store/content/simple-healing/size-grid.jpg", alt: "치수 다이어그램 D/H/C/HD + 상단 8M 표기 예시" },
      { type: "heading", text: "Follow color-band" },
      { type: "text", text: "Pen·Pin·BoneShaper와 동일 색상 밴드로 Healing → Simple Abut. → Final까지 규격을 유지합니다." },
    ],
  },
  "full-package": {
    blurb: "키트 3종 + Abutment 200EA 일괄",
    description: "Initial·Check·Prosthetic Kit 각 1키트, SimpleAbutment2 100EA, SimpleHealing2 100EA.",
    blocks: [
      { type: "heading", text: "500만 패키지 구성" },
      { type: "list", items: ["TheSimple Kit Initial ×1", "TheSimple Kit Check ×1", "TheSimple Kit Prosthetics ×1", "Simple Abut.[Non-Hex]Anti-rotation ×100", "Healing Abut. ×100"] },
      { type: "text", text: "각 구성품 상세·사용법은 해당 단품/키트 상세 페이지를 참고하세요." },
      { type: "image", src: "/store/content/full-package/initial-kit.jpg", alt: "Initial Kit" },
      { type: "image", src: "/store/content/full-package/check-kit.jpg", alt: "Check Kit" },
      { type: "image", src: "/store/content/full-package/prosthetic-kit.jpg", alt: "Prosthetic Kit" },
      { type: "image", src: "/store/content/full-package/simple-abutment-2.jpg", alt: "SimpleAbutment2" },
      { type: "image", src: "/store/content/full-package/simple-healing-2.jpg", alt: "SimpleHealing2" },
    ],
  },
  "kit-case": {
    blurb: "Initial / Check / Prosthetic · 3종",
    description:
      "TheSimple Kit 수납용 케이스. Initial·Check·Prosthetic 키트별로 케이스 형상이 다르며 단가도 다릅니다.",
    specs: [
      { label: "포장단위", value: "1EA" },
      { label: "제조자/제조국", value: "(주)애크로덴트/대한민국" },
      {
        label: "옵션",
        value: "Initial Kit Case · Check Kit Case · Prosthetic Kit Case",
      },
    ],
    blocks: [
      { type: "heading", text: "Kit Case 3종" },
      {
        type: "text",
        text: "시술 키트 구성품을 수납·보관하는 케이스입니다. Initial / Check / Prosthetics 키트에 각각 맞는 케이스를 선택해 주세요.",
      },
      {
        type: "list",
        items: [
          "Initial Kit Case — Initial Kit 전용 (판매가 264,000원)",
          "Check Kit Case — Check Kit 전용 (판매가 220,000원)",
          "Prosthetic Kit Case — Prosthetic Kit 전용 (판매가 220,000원)",
        ],
      },
    ],
  },
};

export function getStoreProductContent(productId: string | undefined) {
  if (!productId) return undefined;
  return STORE_PRODUCT_CONTENT[productId];
}
