BEGIN_PROCESS; Íï?Ù£?; 4;
BEGIN_OPERATION; 546; MarkText; 0;
   CollisionDetection; 6630; 0;  CAPTION; ?ÓÕ??; SOURCE; 2; TECHCODETYPE; 520;
   ReferenceDepthOfCut; 1768; 0.20000000000000001;  HIDDEN; CAPTION; ?ÍÅÊ¥Íïä¢Óø; SOURCE; 2; TECHCODETYPE; 2;
   StockAllowanceFloors; 272; -0.050000000000000003;  CAPTION; ?ú¾åùÕá; SOURCE; 2; TECHCODETYPE; 2;
   CuttingProfiles; 3366; ;  CAPTION; Ê¥Íï?Î©; SOURCE; 2; TECHCODETYPE; 3;
	BEGIN_STRING; 3366;;
		:6,16|6,17|6,18
	END_STRING
   BEGIN_SUB_TECHNOLOGY; 3210; 516; CAPTION; 5??ÓïÛ°ãÒ; SOURCE; 2; TECHCODETYPE; 410;
   ReferenceDepthOfCut; 1768; 5;  CAPTION; ?ÍÅÊ¥Íïä¢Óø; SOURCE; 0; TECHCODETYPE; 2;
   MinimumRampWidth; 3383; 10;  HIDDEN; CAPTION; õÌá³ÞØú¾?Óø; SOURCE; 0; TECHCODETYPE; 2;
   StartPointY; 3394; 0;  HIDDEN; CAPTION; ?ã·ïÃ Y|?ã·ïÃ X,Y; SOURCE; 0; TECHCODETYPE; 2;
   SetLimits; 3391; 0;  HIDDEN; CAPTION; ?öÇùÚïÒ; SOURCE; 0; TECHCODETYPE; 67;
   EntryMovesAngle; 3388; 0;  HIDDEN; CAPTION; ø¶?ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   ArcAngle; 3303; 30;  HIDDEN; CAPTION; ?ûÁÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   ExtensionDistance; 6836; 0;  HIDDEN; CAPTION; æÅãß?Óø; SOURCE; 0; TECHCODETYPE; 2;
   MaximumX; 3385; 100;  HIDDEN; CAPTION; õÌá³X|XõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   EntryMovesType; 3300; 1;  CAPTION; ïÈÐÎ?úþ; SOURCE; 0; TECHCODETYPE; 431;
   RampHeight; 3382; 2;  HIDDEN; CAPTION; Ûöú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   StartPointX; 3393; 0;  HIDDEN; CAPTION; ?ã·ïÃ X|?ã·ïÃ X,Y; SOURCE; 0; TECHCODETYPE; 2;
   HelixDiameter; 3390; 10;  HIDDEN; CAPTION; Õ¢àÁòÁ?; SOURCE; 0; TECHCODETYPE; 2;
   TiltingAngle; 6600; 0;  HIDDEN; CAPTION; ??ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   MaximumY; 3387; 100;  HIDDEN; CAPTION; õÌÓÞY|YõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   ArcRadius; 3302; 5;  HIDDEN; CAPTION; ?ûÁÚâ?; SOURCE; 0; TECHCODETYPE; 2;
   TangentRampAngle; 6835; 0;  HIDDEN; CAPTION; ÞØú¾ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   MinimumX; 3384; 0;  HIDDEN; CAPTION; õÌÓÞX|XõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   RampAngle; 3381; 20;  HIDDEN; CAPTION; ÞØú¾ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   TangentDistance; 3446; 0;  HIDDEN; CAPTION; ï·ú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   PredefinedPoints; 3395; ;  HIDDEN; CAPTION; ?à»ò¦ïÒîÜïÃ; SOURCE; 0; TECHCODETYPE; 3;
	BEGIN_STRING; 3395;;
		:
	END_STRING
   FromPredefinedPoints; 3392; 0;  HIDDEN; CAPTION; ??à»ò¦ïÒîÜïÃ; SOURCE; 0; TECHCODETYPE; 67;
   HelixAngle; 3389; 10;  HIDDEN; CAPTION; Õ¢àÁÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   LateralDistance; 3304; 2;  HIDDEN; CAPTION; ?ú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   MinimumY; 3386; 0;  HIDDEN; CAPTION; õÌá³Y|YõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   VerticalDistance; 3301; 3;  CAPTION; á÷òÁËå?; SOURCE; 0; TECHCODETYPE; 2;
   BEGIN_EXPRESSION
   END_EXPRESSION
	BEGIN_ATTRIBUTES
	END_ATTRIBUTES
   END_SUB_TECHNOLOGY
   BEGIN_SUB_TECHNOLOGY; 3210; 516; CAPTION; 5??ÓïÛ°ãÒ; SOURCE; 2; TECHCODETYPE; 410;
   ReferenceDepthOfCut; 1768; 5;  CAPTION; ?ÍÅÊ¥Íïä¢Óø; SOURCE; 0; TECHCODETYPE; 2;
   MinimumRampWidth; 3383; 10;  CAPTION; õÌá³ÞØú¾?Óø; SOURCE; 0; TECHCODETYPE; 2;
   StartPointY; 3394; 0;  CAPTION; ?ã·ïÃ Y|?ã·ïÃ X,Y; SOURCE; 0; TECHCODETYPE; 2;
   SetLimits; 3391; 0;  CAPTION; ?öÇùÚïÒ; SOURCE; 0; TECHCODETYPE; 67;
   EntryMovesAngle; 3388; 0;  CAPTION; ø¶?ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   ArcAngle; 3303; 30;  CAPTION; ?ûÁÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   ExtensionDistance; 6836; 0;  CAPTION; æÅãß?Óø; SOURCE; 0; TECHCODETYPE; 2;
   MaximumX; 3385; 100;  CAPTION; õÌá³X|XõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   EntryMovesType; 3300; 4;  CAPTION; ïÈÐÎ?úþ; SOURCE; 0; TECHCODETYPE; 431;
   RampHeight; 3382; 2;  CAPTION; Ûöú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   StartPointX; 3393; 0;  CAPTION; ?ã·ïÃ X|?ã·ïÃ X,Y; SOURCE; 0; TECHCODETYPE; 2;
   HelixDiameter; 3390; 10;  CAPTION; Õ¢àÁòÁ?; SOURCE; 0; TECHCODETYPE; 2;
   TiltingAngle; 6600; 0;  CAPTION; ??ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   MaximumY; 3387; 100;  CAPTION; õÌÓÞY|YõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   ArcRadius; 3302; 1;  CAPTION; ?ûÁÚâ?; SOURCE; 0; TECHCODETYPE; 2;
   TangentRampAngle; 6835; 0;  CAPTION; ÞØú¾ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   MinimumX; 3384; 0;  CAPTION; õÌÓÞX|XõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   RampAngle; 3381; 20;  CAPTION; ÞØú¾ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   TangentDistance; 3446; 0;  CAPTION; ï·ú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   PredefinedPoints; 3395; ;  CAPTION; ?à»ò¦ïÒîÜïÃ; SOURCE; 0; TECHCODETYPE; 3;
	BEGIN_STRING; 3395;;
		:
	END_STRING
   FromPredefinedPoints; 3392; 0;  CAPTION; ??à»ò¦ïÒîÜïÃ; SOURCE; 0; TECHCODETYPE; 67;
   HelixAngle; 3389; 10;  CAPTION; Õ¢àÁÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   LateralDistance; 3304; 2;  CAPTION; ?ú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   MinimumY; 3386; 0;  CAPTION; õÌá³Y|YõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   VerticalDistance; 3301; 3;  CAPTION; á÷òÁËå?; SOURCE; 0; TECHCODETYPE; 2;
   BEGIN_EXPRESSION
   END_EXPRESSION
	BEGIN_ATTRIBUTES
	END_ATTRIBUTES
   END_SUB_TECHNOLOGY
   BEGIN_SUB_TECHNOLOGY; 3210; 516; CAPTION; 5??ÓïÛ°ãÒ; SOURCE; 2; TECHCODETYPE; 410;
   ReferenceDepthOfCut; 1768; 5;  CAPTION; ?ÍÅÊ¥Íïä¢Óø; SOURCE; 0; TECHCODETYPE; 2;
   MinimumRampWidth; 3383; 10;  HIDDEN; CAPTION; õÌá³ÞØú¾?Óø; SOURCE; 0; TECHCODETYPE; 2;
   StartPointY; 3394; 0;  HIDDEN; CAPTION; ?ã·ïÃ Y|?ã·ïÃ X,Y; SOURCE; 0; TECHCODETYPE; 2;
   SetLimits; 3391; 0;  CAPTION; ?öÇùÚïÒ; SOURCE; 0; TECHCODETYPE; 67;
   EntryMovesAngle; 3388; 0;  CAPTION; ø¶?ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   ArcAngle; 3303; 30;  HIDDEN; CAPTION; ?ûÁÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   ExtensionDistance; 6836; 0;  HIDDEN; CAPTION; æÅãß?Óø; SOURCE; 0; TECHCODETYPE; 2;
   MaximumX; 3385; 100;  HIDDEN; CAPTION; õÌá³X|XõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   EntryMovesType; 3300; 6;  CAPTION; ïÈÐÎ?úþ; SOURCE; 0; TECHCODETYPE; 431;
   RampHeight; 3382; 2;  HIDDEN; CAPTION; Ûöú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   StartPointX; 3393; 0;  HIDDEN; CAPTION; ?ã·ïÃ X|?ã·ïÃ X,Y; SOURCE; 0; TECHCODETYPE; 2;
   HelixDiameter; 3390; 10;  HIDDEN; CAPTION; Õ¢àÁòÁ?; SOURCE; 0; TECHCODETYPE; 2;
   TiltingAngle; 6600; 0;  HIDDEN; CAPTION; ??ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   MaximumY; 3387; 100;  HIDDEN; CAPTION; õÌÓÞY|YõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   ArcRadius; 3302; 5;  HIDDEN; CAPTION; ?ûÁÚâ?; SOURCE; 0; TECHCODETYPE; 2;
   TangentRampAngle; 6835; 0;  CAPTION; ÞØú¾ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   MinimumX; 3384; 0;  HIDDEN; CAPTION; õÌÓÞX|XõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   RampAngle; 3381; 20;  HIDDEN; CAPTION; ÞØú¾ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   TangentDistance; 3446; 0;  HIDDEN; CAPTION; ï·ú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   PredefinedPoints; 3395; ;  HIDDEN; CAPTION; ?à»ò¦ïÒîÜïÃ; SOURCE; 0; TECHCODETYPE; 3;
	BEGIN_STRING; 3395;;
		:
	END_STRING
   FromPredefinedPoints; 3392; 0;  HIDDEN; CAPTION; ??à»ò¦ïÒîÜïÃ; SOURCE; 0; TECHCODETYPE; 67;
   HelixAngle; 3389; 10;  HIDDEN; CAPTION; Õ¢àÁÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   LateralDistance; 3304; 0.5;  CAPTION; ?ú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   MinimumY; 3386; 0;  HIDDEN; CAPTION; õÌá³Y|YõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   VerticalDistance; 3301; 2;  CAPTION; á÷òÁËå?; SOURCE; 0; TECHCODETYPE; 2;
   BEGIN_EXPRESSION
   END_EXPRESSION
	BEGIN_ATTRIBUTES
	END_ATTRIBUTES
   END_SUB_TECHNOLOGY
   SpindleID; 793; 1;  CAPTION; ñ«?Ù£?; SOURCE; 2; TECHCODETYPE; 1;
   OutputZValue; 1218; 0;  CAPTION; Z??õó; SOURCE; 2; TECHCODETYPE; 118;
   CustomSetting10; 640; 0;  CAPTION; í»ïÒ? 10; SOURCE; 2; TECHCODETYPE; 2;
   UseFeedSpeedKB; 1762; 0;  CAPTION; ÞÅéÄKBM???áÜ; SOURCE; 2; TECHCODETYPE; 67;
   ZCalculation; 1422; 1;  CAPTION; Z ?ß©; SOURCE; 2; TECHCODETYPE; 467;
   4003; 4003; 67;  SOURCE; 0; TECHCODETYPE; 1;
   OptimizationMode; 3323; 0;  HIDDEN; CAPTION; ?ûù; SOURCE; 3; TECHCODETYPE; 496;
   CustomSetting7; 637; 0;  CAPTION; í»ïÒ? 7; SOURCE; 2; TECHCODETYPE; 2;
   FeedratePT; 416; 0.10000000000000001;  CAPTION; ??áã PT|??áã PM, PT; SOURCE; 2; TECHCODETYPE; 2;
   SmoothingDistance; 3405; 0;  HIDDEN; CAPTION; øÁüÁ?ïÈÓïÖØËå?; SOURCE; 2; TECHCODETYPE; 2;
   CustomSetting4; 634; 0;  CAPTION; í»ïÒ? 4; SOURCE; 2; TECHCODETYPE; 2;
   LateralFeedRatePercent; 3201; 100;  CAPTION; ?ú¾?Óï??áãÛÝÝÂÝï; SOURCE; 2; TECHCODETYPE; 2;
   ToolID; 498; ;  CAPTION; ÓïÎý ID; SOURCE; 2; TECHCODETYPE; 3;
	BEGIN_STRING; 498;;
		:T09_Chamfer_D4
	END_STRING
   MaximumLateralOffset; 3371; 0;  HIDDEN; CAPTION; õÌÓÞ?ú¾ø¶öÇ; SOURCE; 2; TECHCODETYPE; 2;
   IncrementalDepth; 175; 0.5;  CAPTION; ï·Þûä¢Óø; SOURCE; 2; TECHCODETYPE; 2;
   AlternateCutDirection; 1705; 0;  CAPTION; ??ï·ÞûÛ°ú¾; SOURCE; 2; TECHCODETYPE; 67;
   TrimCollisionReorganize; 6632; 0;  HIDDEN; CAPTION; î®îòÓïÖØñìãæ??; SOURCE; 2; TECHCODETYPE; 521;
   HolderClearance; 3470; 0;  HIDDEN; CAPTION; ÓïÜ·?ÐÀ; SOURCE; 2; TECHCODETYPE; 2;
   CustomSetting1; 631; 0;  CAPTION; í»ïÒ? 1; SOURCE; 2; TECHCODETYPE; 2;
   Clearance; 172; 2;  CAPTION; äÌîïÍÔÓø; SOURCE; 2; TECHCODETYPE; 2;
   StepPercentOfDiameter; 444; 10;  HIDDEN; CAPTION; ÜÆËå òÁ?îÜ% |ÜÆËå,òÁ?%; SOURCE; 2; TECHCODETYPE; 1;
   ZOffset; 3368; 0;  CAPTION; Zø¶öÇ; SOURCE; 2; TECHCODETYPE; 2;
   BEGIN_SUB_TECHNOLOGY; 6833; 714; CAPTION; 5?÷ÜÓïÛ°ãÒ; SOURCE; 2; TECHCODETYPE; 410;
   ExitMovesType; 6834; 1;  CAPTION; 5?÷ÜÓïÛ°ãÒ ; SOURCE; 0; TECHCODETYPE; 563;
   ReferenceDepthOfCut; 1768; 5;  CAPTION; ?ÍÅÊ¥Íïä¢Óø; SOURCE; 0; TECHCODETYPE; 2;
   MinimumRampWidth; 3383; 10;  HIDDEN; CAPTION; õÌá³ÞØú¾?Óø; SOURCE; 0; TECHCODETYPE; 2;
   EndPointY; 3394; 0;  HIDDEN; CAPTION; ?áÖïÃY|?áÖïÃX,Y; SOURCE; 0; TECHCODETYPE; 2;
   SetLimits; 3391; 0;  HIDDEN; CAPTION; ?öÇùÚïÒ; SOURCE; 0; TECHCODETYPE; 67;
   EntryMovesAngle; 3388; 0;  HIDDEN; CAPTION; ø¶?ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   ArcAngle; 3303; 30;  HIDDEN; CAPTION; ?ûÁÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   ExtensionDistance; 6836; 0;  HIDDEN; CAPTION; æÅãß?Óø; SOURCE; 0; TECHCODETYPE; 2;
   MaximumX; 3385; 100;  HIDDEN; CAPTION; õÌá³X|XõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   RampHeight; 3382; 2;  HIDDEN; CAPTION; Ûöú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   EndPointX; 3393; 0;  HIDDEN; CAPTION; ?áÖïÃX|?áÖïÃX,Y; SOURCE; 0; TECHCODETYPE; 2;
   HelixDiameter; 3390; 10;  HIDDEN; CAPTION; Õ¢àÁòÁ?; SOURCE; 0; TECHCODETYPE; 2;
   TiltingAngle; 6600; 0;  HIDDEN; CAPTION; ??ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   MaximumY; 3387; 100;  HIDDEN; CAPTION; õÌÓÞY|YõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   ArcRadius; 3302; 5;  HIDDEN; CAPTION; ?ûÁÚâ?; SOURCE; 0; TECHCODETYPE; 2;
   TangentRampAngle; 6835; 0;  HIDDEN; CAPTION; ÞØú¾ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   MinimumX; 3384; 0;  HIDDEN; CAPTION; õÌÓÞX|XõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   RampAngle; 3381; 20;  HIDDEN; CAPTION; ÞØú¾ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   TangentDistance; 3446; 0;  HIDDEN; CAPTION; ï·ú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   PredefinedPoints; 3395; ;  HIDDEN; CAPTION; ?à»ò¦ïÒîÜïÃ; SOURCE; 0; TECHCODETYPE; 3;
	BEGIN_STRING; 3395;;
		:
	END_STRING
   FromPredefinedPoints; 3392; 0;  HIDDEN; CAPTION; ??à»ò¦ïÒîÜïÃ; SOURCE; 0; TECHCODETYPE; 67;
   HelixAngle; 3389; 10;  HIDDEN; CAPTION; Õ¢àÁÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   LateralDistance; 3304; 2;  HIDDEN; CAPTION; ?ú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   MinimumY; 3386; 0;  HIDDEN; CAPTION; õÌá³Y|YõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   VerticalDistance; 3301; 3;  CAPTION; á÷òÁËå?; SOURCE; 0; TECHCODETYPE; 2;
   BEGIN_EXPRESSION
   END_EXPRESSION
	BEGIN_ATTRIBUTES
	END_ATTRIBUTES
   END_SUB_TECHNOLOGY
   BEGIN_SUB_TECHNOLOGY; 6833; 714; CAPTION; 5?÷ÜÓïÛ°ãÒ; SOURCE; 2; TECHCODETYPE; 410;
   ExitMovesType; 6834; 4;  CAPTION; 5?÷ÜÓïÛ°ãÒ ; SOURCE; 0; TECHCODETYPE; 563;
   ReferenceDepthOfCut; 1768; 5;  CAPTION; ?ÍÅÊ¥Íïä¢Óø; SOURCE; 0; TECHCODETYPE; 2;
   MinimumRampWidth; 3383; 10;  CAPTION; õÌá³ÞØú¾?Óø; SOURCE; 0; TECHCODETYPE; 2;
   EndPointY; 3394; 0;  CAPTION; ?áÖïÃY|?áÖïÃX,Y; SOURCE; 0; TECHCODETYPE; 2;
   SetLimits; 3391; 0;  CAPTION; ?öÇùÚïÒ; SOURCE; 0; TECHCODETYPE; 67;
   EntryMovesAngle; 3388; 0;  CAPTION; ø¶?ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   ArcAngle; 3303; 30;  CAPTION; ?ûÁÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   ExtensionDistance; 6836; 0;  CAPTION; æÅãß?Óø; SOURCE; 0; TECHCODETYPE; 2;
   MaximumX; 3385; 100;  CAPTION; õÌá³X|XõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   RampHeight; 3382; 2;  CAPTION; Ûöú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   EndPointX; 3393; 0;  CAPTION; ?áÖïÃX|?áÖïÃX,Y; SOURCE; 0; TECHCODETYPE; 2;
   HelixDiameter; 3390; 10;  CAPTION; Õ¢àÁòÁ?; SOURCE; 0; TECHCODETYPE; 2;
   TiltingAngle; 6600; 0;  CAPTION; ??ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   MaximumY; 3387; 100;  CAPTION; õÌÓÞY|YõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   ArcRadius; 3302; 1;  CAPTION; ?ûÁÚâ?; SOURCE; 0; TECHCODETYPE; 2;
   TangentRampAngle; 6835; 0;  CAPTION; ÞØú¾ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   MinimumX; 3384; 0;  CAPTION; õÌÓÞX|XõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   RampAngle; 3381; 20;  CAPTION; ÞØú¾ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   TangentDistance; 3446; 0;  CAPTION; ï·ú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   PredefinedPoints; 3395; ;  CAPTION; ?à»ò¦ïÒîÜïÃ; SOURCE; 0; TECHCODETYPE; 3;
	BEGIN_STRING; 3395;;
		:
	END_STRING
   FromPredefinedPoints; 3392; 0;  CAPTION; ??à»ò¦ïÒîÜïÃ; SOURCE; 0; TECHCODETYPE; 67;
   HelixAngle; 3389; 10;  CAPTION; Õ¢àÁÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   LateralDistance; 3304; 2;  CAPTION; ?ú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   MinimumY; 3386; 0;  CAPTION; õÌá³Y|YõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   VerticalDistance; 3301; 3;  CAPTION; á÷òÁËå?; SOURCE; 0; TECHCODETYPE; 2;
   BEGIN_EXPRESSION
   END_EXPRESSION
	BEGIN_ATTRIBUTES
	END_ATTRIBUTES
   END_SUB_TECHNOLOGY
   BEGIN_SUB_TECHNOLOGY; 6833; 714; CAPTION; 5?÷ÜÓïÛ°ãÒ; SOURCE; 2; TECHCODETYPE; 410;
   ExitMovesType; 6834; 6;  CAPTION; 5?÷ÜÓïÛ°ãÒ ; SOURCE; 0; TECHCODETYPE; 563;
   ReferenceDepthOfCut; 1768; 5;  CAPTION; ?ÍÅÊ¥Íïä¢Óø; SOURCE; 0; TECHCODETYPE; 2;
   MinimumRampWidth; 3383; 10;  HIDDEN; CAPTION; õÌá³ÞØú¾?Óø; SOURCE; 0; TECHCODETYPE; 2;
   EndPointY; 3394; 0;  HIDDEN; CAPTION; ?áÖïÃY|?áÖïÃX,Y; SOURCE; 0; TECHCODETYPE; 2;
   SetLimits; 3391; 0;  CAPTION; ?öÇùÚïÒ; SOURCE; 0; TECHCODETYPE; 67;
   EntryMovesAngle; 3388; 0;  CAPTION; ø¶?ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   ArcAngle; 3303; 30;  HIDDEN; CAPTION; ?ûÁÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   ExtensionDistance; 6836; 0;  HIDDEN; CAPTION; æÅãß?Óø; SOURCE; 0; TECHCODETYPE; 2;
   MaximumX; 3385; 100;  HIDDEN; CAPTION; õÌá³X|XõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   RampHeight; 3382; 2;  HIDDEN; CAPTION; Ûöú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   EndPointX; 3393; 0;  HIDDEN; CAPTION; ?áÖïÃX|?áÖïÃX,Y; SOURCE; 0; TECHCODETYPE; 2;
   HelixDiameter; 3390; 10;  HIDDEN; CAPTION; Õ¢àÁòÁ?; SOURCE; 0; TECHCODETYPE; 2;
   TiltingAngle; 6600; 0;  HIDDEN; CAPTION; ??ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   MaximumY; 3387; 100;  HIDDEN; CAPTION; õÌÓÞY|YõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   ArcRadius; 3302; 5;  HIDDEN; CAPTION; ?ûÁÚâ?; SOURCE; 0; TECHCODETYPE; 2;
   TangentRampAngle; 6835; 0;  CAPTION; ÞØú¾ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   MinimumX; 3384; 0;  HIDDEN; CAPTION; õÌÓÞX|XõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   RampAngle; 3381; 20;  HIDDEN; CAPTION; ÞØú¾ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   TangentDistance; 3446; 0;  HIDDEN; CAPTION; ï·ú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   PredefinedPoints; 3395; ;  HIDDEN; CAPTION; ?à»ò¦ïÒîÜïÃ; SOURCE; 0; TECHCODETYPE; 3;
	BEGIN_STRING; 3395;;
		:
	END_STRING
   FromPredefinedPoints; 3392; 0;  HIDDEN; CAPTION; ??à»ò¦ïÒîÜïÃ; SOURCE; 0; TECHCODETYPE; 67;
   HelixAngle; 3389; 10;  HIDDEN; CAPTION; Õ¢àÁÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   LateralDistance; 3304; 0.5;  CAPTION; ?ú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   MinimumY; 3386; 0;  HIDDEN; CAPTION; õÌá³Y|YõÌá³,õÌÓÞ; SOURCE; 0; TECHCODETYPE; 2;
   VerticalDistance; 3301; 2;  CAPTION; á÷òÁËå?; SOURCE; 0; TECHCODETYPE; 2;
   BEGIN_EXPRESSION
   END_EXPRESSION
	BEGIN_ATTRIBUTES
	END_ATTRIBUTES
   END_SUB_TECHNOLOGY
   EnableSmoothing; 3365; 0;  HIDDEN; CAPTION; ÞÅÓïÖØøÁüÁ; SOURCE; 2; TECHCODETYPE; 522;
   StepOver; 217; 0.20000000000000001;  HIDDEN; CAPTION; ÜÆËå|ÜÆËå,òÁ?%; SOURCE; 3; TECHCODETYPE; 2;
   OffsetSideComputer; 234; 1;  CAPTION; ?Ëì??Û°ú¾; SOURCE; 2; TECHCODETYPE; 214;
   TurretID; 792; 1;  CAPTION; Óï÷²Ù£?; SOURCE; 2; TECHCODETYPE; 1;
   AutoTilt; 3410; 0;  CAPTION; í»?ù­?; SOURCE; 2; TECHCODETYPE; 67;
   CustomSetting9; 639; 0;  CAPTION; í»ïÒ? 9; SOURCE; 2; TECHCODETYPE; 2;
   SpindleSpeedSPM; 418; 11;  CAPTION; Ê¥Íï?áÜ SPM|Ê¥Íï?áÜ RPM, SPM; SOURCE; 2; TECHCODETYPE; 1;
   ZPosition; 3325; 0;  HIDDEN; CAPTION; Z êÈöÇ; SOURCE; 2; TECHCODETYPE; 2;
   MaxDistanceBetweenPoints; 3322; 0.10000000000000001;  HIDDEN; CAPTION; ïÃñý?õÌÓÞËå?; SOURCE; 2; TECHCODETYPE; 2;
   CustomSetting6; 636; 0;  CAPTION; í»ïÒ? 6; SOURCE; 2; TECHCODETYPE; 2;
   RetractOptimization; 3203; 2;  CAPTION; õÌ?ûùüÞ÷Ü; SOURCE; 2; TECHCODETYPE; 456;
   TypeOfCut; 432; ;  HIDDEN; CAPTION; Ê¥Íï?úþ; SOURCE; 2; TECHCODETYPE; 3;
	BEGIN_STRING; 432;;
		:
	END_STRING
   SpindleSpeedRPM; 194; 1751;  CAPTION; Ê¥Íï?áÜ RPM|Ê¥Íï?áÜ RPM, SPM; SOURCE; 3; TECHCODETYPE; 1;
   Comment; 7; ;  CAPTION; ñ¼?; SOURCE; 2; TECHCODETYPE; 3;
	BEGIN_STRING; 7;;
		:
	END_STRING
   OverlapDistance; 3373; 0;  CAPTION; ñì?Ëå?; SOURCE; 2; TECHCODETYPE; 2;
   CutterCompNC; 245; 0;  CAPTION; NC??ÓïÎýÚâ?; SOURCE; 2; TECHCODETYPE; 5;
   EnableRTCP; 3200; 0;  CAPTION; ??RTCP; SOURCE; 3; TECHCODETYPE; 67;
   CustomSetting3; 633; 0;  CAPTION; í»ïÒ? 3; SOURCE; 2; TECHCODETYPE; 2;
   FeedratePM; 191; 350.20000000000005;  CAPTION; ??áã PM|??áã PM, PT; SOURCE; 3; TECHCODETYPE; 2;
   OffsetRegisterValue; 225; 0;  CAPTION; ???; SOURCE; 2; TECHCODETYPE; 2;
   FinalDepth; 3370; 0;  CAPTION; ?ã·ä¢Óø; SOURCE; 2; TECHCODETYPE; 2;
   TrimCollisionEnableJump; 6631; 0;  HIDDEN; CAPTION; ÊÎàï?ÓÕ?Ô¯Óï; SOURCE; 2; TECHCODETYPE; 67;
   FullClearance; 443; 20;  CAPTION; ??äÌîïÍÔÓø; SOURCE; 2; TECHCODETYPE; 2;
   OperationName; 613; ;  CAPTION; ðÃíÂÙ£?; SOURCE; 2; TECHCODETYPE; 3;
	BEGIN_STRING; 613;;
		:MarkText
	END_STRING
   BEGIN_SUB_TECHNOLOGY; 3214; 515; CAPTION; 5 ????ïÈ; SOURCE; 2; TECHCODETYPE; 410;
   ReferenceDepthOfCut; 1768; 5;  CAPTION; ?ÍÅÊ¥Íïä¢Óø; SOURCE; 0; TECHCODETYPE; 2;
   OutArcRadius; 3400; 2;  HIDDEN; CAPTION; ï·õó?ûÁÚâ?|?ûÁÚâ?(ï·ìý,ï·õó); SOURCE; 0; TECHCODETYPE; 2;
   MinimumRampWidth; 3383; 5;  HIDDEN; CAPTION; õÌá³ÞØú¾?Óø; SOURCE; 0; TECHCODETYPE; 2;
   StartArcAngle; 3315; 30;  HIDDEN; CAPTION; ?ûÁÑÃã·ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   InRampLength; 3397; 0;  HIDDEN; CAPTION; ÞØú¾ï·ìý?Óø|ÞØú¾?Óø(ï·ìý,ï·õó); SOURCE; 0; TECHCODETYPE; 2;
   OutArcAngle; 3402; 45;  HIDDEN; CAPTION; ï·õó?ûÁÊÇÓø|?ûÁÊÇÓø(ï·ìý,ï·õó); SOURCE; 0; TECHCODETYPE; 2;
   InRampAngle; 3399; 0;  HIDDEN; CAPTION; ÞØú¾ï·ìýÊÇÓø|ÞØú¾ÊÇÓø(ï·ìý,ï·õó); SOURCE; 0; TECHCODETYPE; 2;
   EndArcRadius; 3314; 5;  HIDDEN; CAPTION; ?ò­?ûÁÚâ?; SOURCE; 0; TECHCODETYPE; 2;
   OutRampLength; 3396; 0;  HIDDEN; CAPTION; ÞØú¾ï·õó?Óø|ÞØú¾?Óø(ï·ìý,ï·õó); SOURCE; 0; TECHCODETYPE; 2;
   MaximumLinkDistance; 3311; 0.01;  CAPTION; õÌÓÞ?ïÈËå?; SOURCE; 2; TECHCODETYPE; 2;
   MaxZDifference; 3407; 10;  HIDDEN; CAPTION; õÌÓÞZó¬?; SOURCE; 0; TECHCODETYPE; 2;
   MinimumLoopWidth; 3404; 1;  HIDDEN; CAPTION; õÌá³??Óø; SOURCE; 0; TECHCODETYPE; 2;
   InArcRadius; 3401; 2;  HIDDEN; CAPTION; ï·ìý?ûÁÚâ?|?ûÁÚâ?(ï·ìý,ï·õó); SOURCE; 0; TECHCODETYPE; 2;
   EndArcAngle; 3316; 30;  HIDDEN; CAPTION; ?ûÁ?ò­ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   OutRampAngle; 3398; 0;  HIDDEN; CAPTION; ÞØú¾ï·õóÊÇÓø|ÞØú¾ÊÇÓø(ï·ìý,ï·õó); SOURCE; 0; TECHCODETYPE; 2;
   RampAngle; 3381; 5;  CAPTION; ÞØú¾ÊÇÓø; SOURCE; 0; TECHCODETYPE; 2;
   StartArcRadius; 3313; 5;  HIDDEN; CAPTION; ÑÃã·?ûÁÚâ?; SOURCE; 0; TECHCODETYPE; 2;
   FeedLinkType; 3310; 7;  CAPTION; ???ïÈ?úþ; SOURCE; 0; TECHCODETYPE; 433;
   MaxZDifferenceAcross; 3406; 10;  HIDDEN; CAPTION; õÌÓÞ?ú¾Zó¬?; SOURCE; 0; TECHCODETYPE; 2;
   LateralDistance; 3304; 2;  CAPTION; ?ú¾Ëå?; SOURCE; 0; TECHCODETYPE; 2;
   InArcAngle; 3403; 45;  HIDDEN; CAPTION; ï·ìý?ûÁÊÇÓø|?ûÁÊÇÓø(ï·ìý,ï·õó); SOURCE; 0; TECHCODETYPE; 2;
   VerticalDistance; 3318; 2;  HIDDEN; CAPTION; á÷òÁËå?; SOURCE; 0; TECHCODETYPE; 2;
   BEGIN_EXPRESSION
   END_EXPRESSION
	BEGIN_ATTRIBUTES
	END_ATTRIBUTES
   END_SUB_TECHNOLOGY
   CutUpHillOnly; 3367; 0;  CAPTION; ñþÊ¥Íïß¾ã®?æ´; SOURCE; 2; TECHCODETYPE; 67;
   HeadID; 797; 1;  CAPTION; ÷×Ô³ID; SOURCE; 2; TECHCODETYPE; 1;
   OffsetToolRadius; 780; 0;  CAPTION; ?Ëì??ÓïÎýÚâ?; SOURCE; 2; TECHCODETYPE; 67;
   ShankClearance; 3225; 0;  HIDDEN; CAPTION; ÓïÊÒ?ÐÀ; SOURCE; 2; TECHCODETYPE; 2;
   MaximumTiltAngle; 3412; 20;  HIDDEN; CAPTION; õÌÓÞ?ÞØÊÇÓø; SOURCE; 2; TECHCODETYPE; 2;
   StockAllowanceWalls; 233; 0;  CAPTION; ?ú¾åùÕá; SOURCE; 2; TECHCODETYPE; 2;
   ToolCompensation; 1284; 0;  CAPTION; ÓïÎý??; SOURCE; 2; TECHCODETYPE; 67;
   CustomSetting8; 638; 0;  CAPTION; í»ïÒ? 8; SOURCE; 2; TECHCODETYPE; 2;
   Tolerance; 1046; 0.01;  CAPTION; Íëó¬; SOURCE; 2; TECHCODETYPE; 2;
   LimitDistanceBetweenPoints; 3321; 0;  CAPTION; ùÚð¤ïÃñý?Ëå?; SOURCE; 2; TECHCODETYPE; 67;
   CustomSetting5; 635; 0;  CAPTION; í»ïÒ? 5; SOURCE; 2; TECHCODETYPE; 2;
   PlungeFeedRatePercent; 3202; 100;  CAPTION; á÷òÁù»Óï??áãÛÝÝÂÝï; SOURCE; 2; TECHCODETYPE; 2;
   CutTowardProfile; 3372; 0;  HIDDEN; CAPTION; ðÈú¾?Î©Ê¥Íï; SOURCE; 2; TECHCODETYPE; 67;
   EnableCheckCollisionsWithStock; 6633; 0;  HIDDEN; CAPTION; ??ÊÎàïÙ¾?; SOURCE; 2; TECHCODETYPE; 67;
   CollisionTolerance; 3471; 0.10000000000000001;  HIDDEN; CAPTION; ÊÎàïÍëó¬; SOURCE; 2; TECHCODETYPE; 2;
   CustomSetting2; 632; 0;  CAPTION; í»ïÒ? 2; SOURCE; 2; TECHCODETYPE; 2;
   OffsetRegisterNC; 122; 0;  CAPTION; ÓïÎý???; SOURCE; 2; TECHCODETYPE; 1;
   StartingDepth; 3369; 0;  CAPTION; õÌ?ä¢Óø; SOURCE; 2; TECHCODETYPE; 2;
   BEGIN_EXPRESSION
     175; CoverttoSysUnit(Tool1("ToolDiameter").value ,Tool1("ToolUnit").value )*0.25
     172; im(0.1,2)
     3322; im(.005,.1)
     443; FullClearanceFromFreeFormFeaturePartAndCheck(Feature,1,20)
   END_EXPRESSION
	BEGIN_ATTRIBUTES
	END_ATTRIBUTES
END_OPERATION
